Added Windows support to python auth example files
CDCgov/prime-reportstream pull request #10473
Opened 2023-07-17 16:04 UTC by thetaurean

Quality of life improvements for Windows users of the `generate-jwt-example` example project which helps onboard senders to the ReportStream ecosystem. This should get windows users mostly over the fence and also includes some improvements for *nix users (pipx over manually managed virtualenvs)

**If you are suggesting a fix for a currently exploitable issue, please disclose the issue to the prime-reportstream team directly outside of GitHub instead of filing a PR, so we may immediately patch the affected systems before a disclosure. See [SECURITY.md/Reporting a Vulnerability](https://github.com/CDCgov/prime-reportstream/blob/master/SECURITY.md#reporting-a-vulnerability) for more information.**

Test Steps:
1. Follow the steps in `examples/generate-jwt-python` directory on windows and *nix and make sure it works

## Changes
- Use pipenv for dependency and virtualenv management

## Checklist

### Testing
- [X] Tested locally?
- [x] No Changes ~~Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?~~
- [x] No Changes ~~(For Changes to /frontend-react/...) Ran `npm run lint:write`?~~
- [x] N/A ~~Added tests?~~

### Process
- [x] Are there licensing issues with any new dependencies introduced? No
- [x] Includes a summary of what a code reviewer should test/verify? Yes
- [x] N/A ~~Updated the release notes?~~
- [x] N/A ~~Database changes are submitted as a separate PR?~~
- [x] N/A ~~DevOps team has been notified if PR requires ops support?~~

## Linked Issues
- Fixes #10201 

## Specific Security-related subjects a reviewer should pay specific attention to
No to all questions

2023-07-18 12:29 UTC, snesm approved these changes

2023-07-18 13:07 UTC, mkalish requested changes
Hit a couple of issues, but looking good!  I wasn't able to actually get through running the script on windows though

2023-07-18 13:07 UTC, mkalish commented on prime-router/examples/generate-jwt-python/requirements.txt
Looks like this file isn't used?

2023-07-18 13:07 UTC, mkalish commented on prime-router/examples/generate-jwt-python/README.md
> +      python3.exe -m pipx install PyJWT cryptography
This didn't work for me.  I hid two errors:

- it looks like pipx didn't like passing multiple options to install, so at first the command didn't run at all
- I was able to run `python3.exe -m pipx install PyJWT`, but `python3.exe -m pipx install cryptography` did not work, saying there was no associated package

2023-07-20 14:54 UTC, mkalish commented
@thetaurean Just confirming this is ready for a re-review?

2023-07-21 12:14 UTC, mkalish approved these changes
Good to merge, though I think it would make sense to maybe follow up and see if we can drop the `python3` everywhere.  Python2 is no longer supported and most folks should have python pointing at v3

2023-07-21 12:14 UTC, mkalish commented on prime-router/examples/generate-jwt-python/README.md
> +  python3.exe .\generate-jwt.py
On my windows machine this didn't quite work... I had to do
```suggestion
  python .\generate-jwt.py
```

2023-07-24 14:46 UTC, merged