8912: handling duplicate items design
CDCgov/prime-reportstream pull request #10689
Opened 2023-07-31 19:58 UTC by mkalish

This PR adds a design for how to handle duplicate items going through report stream

Test Steps:
n/a

## Changes
- Adds the design

## Checklist

### Testing
- [ ] Tested locally?
- [ ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] (For Changes to /frontend-react/...) Ran `npm run lint:write`? 
- [ ] Added tests?

### Process
- [ ] Are there licensing issues with any new dependencies introduced?
- [ ] Includes a summary of what a code reviewer should test/verify?
- [ ] Updated the release notes?
- [ ] Database changes are submitted as a separate PR?
- [ ] DevOps team has been notified if PR requires ops support?

## Linked Issues
- Fixes #issue

## To Be Done
*Create GitHub issues to track the work remaining, if any*
- #issue

## Specific Security-related subjects a reviewer should pay specific attention to
- Does this PR introduce new endpoints?
    - new endpoint A
    - new endpoint B
- Does this PR include changes in authentication and/or authorization of existing endpoints?
- Does this change introduce new dependencies that need vetting?
- Does this change require changes to our infrastructure?
- Does logging contain sensitive data?
- Does this PR include or remove any sensitive information itself?

If you answered '_yes_' to any of the questions above, conduct a detailed Review that addresses at least:

- What are the potential security threats and mitigations? Please list the _STRIDE_ threats and how they are mitigated
    - **S**poofing (faking authenticity)
        - Threat _T_, which could be achieved by _A_, is mitigated by _M_
    - **T**ampering (influence or sabotage the integrity of information, data, or system)
    - **R**epudiation (the ability to dispute the origin or originator of an action)
    - **I**nformation disclosure (data made available to entities who should not have it)
    - **D**enial of service (make a resource unavailable)
    - **E**levation of Privilege (reduce restrictions that apply or gain privileges one should not have)
- Have you ensured logging does not contain sensitive data?
- Have you received any additional approvals needed for this change?

2023-08-21 14:30 UTC, arnejduranovic requested changes
I think this is a good approach, given the unknowns you list (I've forwarded this doc to the routing disco sprint team @avnieldravid). Just left some minor comments for spelling and a couple clarifying questions.

2023-08-21 14:30 UTC, arnejduranovic commented on prime-router/docs/design/features/0006-handling-sending-duplicate-items.md
> +- An item hash is calculated used the contents of the item (using all the columns as the input to a message digest)
Using all the columns of what? The metadata table?

2023-08-21 14:30 UTC, arnejduranovic commented on prime-router/docs/design/features/0006-handling-sending-duplicate-items.md
> +written than processes any items out of the that queue once the underlying problem has been solved.
```suggestion
written that processes any items out of the queue once the underlying problem has been solved.
```

2023-08-21 20:43 UTC, mkalish commented on prime-router/docs/design/features/0006-handling-sending-duplicate-items.md
> +- An item hash is calculated used the contents of the item (using all the columns as the input to a message digest)
I think we'll use the entirety of the contents.  So for HL7 that would be all the columns, for FHIR we would need to write something new.

See https://github.com/CDCgov/prime-reportstream/blob/5ba66d92ae9ec48593d7924603bdb3f7209d2bdd/prime-router/src/main/kotlin/Report.kt#L1284

2023-08-21 20:44 UTC, mkalish commented on prime-router/docs/design/features/0006-handling-sending-duplicate-items.md
> +By calculating an item hash at every step, the system can quickly detect whether an item has been sent to a receiver. This
I think we would want to use the item hash rather than the report hash because of that issue right?

2023-08-21 20:45 UTC, mkalish commented on prime-router/docs/design/features/0006-handling-sending-duplicate-items.md
> +By calculating an item hash at every step, the system can quickly detect whether an item has been sent to a receiver. This
The hash will be stored with item_lineage as it is now and we can continue to use the HL7 method and will need to add one for FHIR

2023-08-22 21:45 UTC, mkalish commented
BTY @arnejduranovic

2023-08-24 13:53 UTC, arnejduranovic approved these changes

2023-08-24 14:44 UTC, merged