update-cicd-pipeline-jdk-17
CDCgov/prime-reportstream pull request #10931
Opened 2023-08-16 15:40 UTC by lucasdze

This PR is to Update CI\CD Pipeline to use Java 17

2023-08-16 16:02 UTC, jack-h-wang requested changes
The action hash for sonarcloud needs to be updated as well.

2023-08-16 19:18 UTC, jack-h-wang commented on prime-router/Dockerfile.build
Please leave updates to `prime-router` to the Platform team. Updates of this nature require more engineer coordination.

2023-08-16 19:25 UTC, snesm commented on prime-router/Dockerfile.build
I believe that several changes here may affect prime-router.  Should these change be merged with any existing branch?

2023-08-16 19:56 UTC, jack-h-wang commented on prime-router/Dockerfile.build
I don't think there needs to be any change to `prime-router` needed to migrate the CI/CD pipeline to Java 17. The work to make sure the codebase can be built to target Java 17 is a separate unit of work entirely. We just need the CI/CD pipeline to support Java 17 so this work can proceed.

2023-08-17 14:29 UTC, jack-h-wang requested changes
As previously commented, please leave changes to `prime-router` for the Platform team; the backend was building successfully on the updated CICD without this change, and any adjustments need to be coordinated among all engineering teams. Additionally, the SonarCloud Java 11 warning should no longer be appearing in comments.

2023-08-17 14:29 UTC, jack-h-wang commented on .github/workflows/sonarcloud_master.yml
Please update [the action hash for `sonarcloud-github-action`](https://github.com/CDCgov/prime-reportstream/blob/master/.github/workflows/sonarcloud_master.yml#L58).

2023-08-17 14:29 UTC, jack-h-wang commented on prime-router/Dockerfile.build
> +ARG JAVA_VERSION=17
Please revert this change for now.

2023-08-17 14:29 UTC, jack-h-wang commented on prime-router/Dockerfile.dev
> +ARG JAVA_VERSION=17
Please revert this change for now.

2023-08-17 17:43 UTC, lucasdze commented on prime-router/Dockerfile.build
> +# --build-arg JAVA_VERSION=17           - The version of the JDK (and thus JRE) you want to build against/with
reverted

2023-08-17 17:43 UTC, lucasdze commented on prime-router/Dockerfile.build
> +ARG JAVA_VERSION=17
reverted

2023-08-17 17:45 UTC, lucasdze commented on prime-router/Dockerfile.dev
> +ARG JAVA_VERSION=17
reverted

2023-08-17 17:48 UTC, lucasdze commented on prime-router/Dockerfile.build
@jack-h-wang Please review the latest changes

2023-08-17 17:51 UTC, lucasdze commented on .github/workflows/sonarcloud_master.yml
@jack-h-wang 
We cant find a commit on sonarcloud-github-action action related to java 17. So we dont really know what hash to update to here. Any suggestion?

2023-08-17 19:13 UTC, jack-h-wang commented on .github/workflows/sonarcloud_master.yml
@lucasdze Per the [update notes](https://community.sonarsource.com/t/java-11-is-deprecated-as-a-runtime-env-to-scan-your-projects/96597) it just needs to be a release tagged 2.0.0 or later.

2023-08-18 14:37 UTC, snesm commented on .github/workflows/sonarcloud_master.yml
Long term statistics for SonarCloud Kotlin require that we build the back end and generate coverage reports even when building and testing the front end (building the back end does not require this).  SonarCloud uses the generated Jar and coverage reports for part of its testing. This Jar is built with a specific version of the JDK. We use the same JDK to run the scan (from setup-java).

2023-08-21 19:53 UTC, jack-h-wang commented
Closing in favor of #10992.

2023-08-21 19:53 UTC, closed without merging