java 11 to 17
CDCgov/prime-reportstream pull request #11141
Opened 2023-08-29 21:14 UTC by JosiahSiegel

This PR updates build environments to use Java 17, as well as replaces the usage of an outdated docker image with a local build file.

Test Steps:
1. Run a docker hub build

## Changes
- updates build environments to use Java 17
- replaces the usage of an outdated docker image with a local build file
- Consolidate workflows to fetch from same java build action

## Linked Issues
- Fixes #11011

2023-08-30 19:32 UTC, MauriceReeves-usds reviewed
@JosiahSiegel I noticed in the `build.gradle.kts` that the Kotlin versions are not aligned. One spot says `1.8.22` and another says `1.9.10`. Those should probably be aligned.

2023-08-30 19:55 UTC, jack-h-wang commented
@JosiahSiegel I would suggest building this off the work done in #10992

2023-08-31 19:19 UTC, jack-h-wang commented on prime-router/build.gradle.kts
> -    id("com.microsoft.azure.azurefunctions") version "1.13.0"
This seems to be reverting a recently merged dependabot update. We should probably leave this alone.

2023-09-08 17:13 UTC, snesm requested changes

2023-09-08 17:13 UTC, snesm commented on .github/actions/build-backend/action.yml
> +
These steps were previously a separate job.  They are likely to add 10 min. to the full build time.

2023-09-08 17:13 UTC, snesm commented on .github/workflows/build_hub.yml
> +      - name: Build backend
The entire docker_build_test job seems unnecessary since you've moved all the steps to build-backend.

2023-09-08 17:15 UTC, snesm commented
FYI: jvm updates in [progress](https://github.com/CDCgov/prime-reportstream/pull/11227)

2023-09-08 18:26 UTC, snesm commented
> > FYI: jvm updates in [progress](https://github.com/CDCgov/prime-reportstream/pull/11227)
> 
> @jack-h-wang @MauriceReeves-usds @snesm @luis-pabon-tf . Did you want to wait on the JVM update above before merging Java 17?

I believe the kotlin (related) JVM is independent except this PR unifies on 1.8.22, and https://github.com/CDCgov/prime-reportstream/pull/11227 unifies on 1.9.10.

Either is probably better than the current mixed versions in master.

2023-09-08 18:31 UTC, snesm approved these changes

2023-09-08 20:51 UTC, jack-h-wang requested changes
One of the SonarCloud action hashes was still set to the older Java 11 release. Not sure if there's an easier way of unifying all the instances of SonarCloud scanning behind a single action hash, but I've highlighted all the ones I could find and filled in the latest one.

2023-09-08 20:51 UTC, jack-h-wang commented on .github/actions/build-backend/action.yml
> +      uses: sonarsource/sonarcloud-github-action@db501078e936e4b4c8773d1bb949ba9ddb7b6b6a
```suggestion
      uses: sonarsource/sonarcloud-github-action@c25d2e7e3def96d0d1781000d3c429da22cd6252
```

2023-09-08 20:51 UTC, jack-h-wang commented on .github/actions/build-frontend/action.yml
> +      uses: sonarsource/sonarcloud-github-action@4b4d7634dab97dcee0b75763a54a6dc92a9e6bc1
```suggestion
      uses: sonarsource/sonarcloud-github-action@c25d2e7e3def96d0d1781000d3c429da22cd6252
```

2023-09-08 20:51 UTC, jack-h-wang commented on .github/workflows/sonarcloud_master.yml
> +        uses: sonarsource/sonarcloud-github-action@4b4d7634dab97dcee0b75763a54a6dc92a9e6bc1
```suggestion
        uses: sonarsource/sonarcloud-github-action@c25d2e7e3def96d0d1781000d3c429da22cd6252
```

2023-09-09 17:51 UTC, jack-h-wang approved these changes

2023-09-11 15:06 UTC, snesm commented on .github/actions/sonarcloud/action.yml
SonarCloud scans are fragile.  The key seems to be providing the required build outputs.  Running the scans without the required build will **delete** SonarCloud data.

2023-09-11 20:25 UTC, merged