Fix repeated ReportFile download in Batch step for UP
CDCgov/prime-reportstream pull request #11483
Opened 2023-09-22 14:29 UTC by thetaurean

This PR adds a parameter to handleBatchEvent that controls whether content is downloaded in order to prevent duplicate downloads in the UP.

Test Steps:
1. Running smoke tests is sufficient

## Changes
- Added `fetchContent` parameter to `handleBatchEvent` (passed to `createHeader`)
- Updated tests

## Checklist

### Testing
- [x] Tested locally?
- [x] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] ~~Added~~ Modified tests?

## Linked Issues
- Fixes #11370

2023-09-28 15:39 UTC, arnejduranovic requested changes

2023-09-28 15:39 UTC, arnejduranovic commented on prime-router/src/main/kotlin/azure/BatchFunction.kt
> +                workflowEngine.handleBatchEvent(event, maxBatchSize, backstopTime, !receiver.topic.isUniversalPipeline)
I'm not too sure about this solution, it seems kind of unmaintainable to me, given the possibility for having to support other pipelines in the future. Generally, we should stay away sprinkling pipeline-based conditionals throughout the code. We have the` !receiver.topic.isUniversalPipeline` check here and then in the trailing lambda we do:
```
if (receiver.topic.isUniversalPipeline) {
    batchUniversalData(validHeaders, actionHistory, receiver, txn)
}
```

Why don't we just update `batchUniversalData` to NOT download the files again? Furthermore, why does handleBatchEvent only need to run for universal pipeline? There seem to be deeper issues here that we should look into/resolve.

2023-10-05 17:00 UTC, mkalish reviewed
Changes look good to me!  I'll pull down and test with a final review after the conflicts are resolved.

2023-10-06 16:54 UTC, mkalish approved these changes
LGTM!  Ran the smoke tests and everything passed locally

2023-10-11 19:55 UTC, arnejduranovic approved these changes

2023-10-11 22:09 UTC, merged