Introduce IntelliJ formatting settings, update ktlint and plugin
CDCgov/prime-reportstream pull request #11727
Opened 2023-10-11 00:08 UTC by jimmyfagan

This PR adds configs and IDE settings to the repo to establish consistent formatting settings for json/fhir, yml, and kotlin files. As part of this, it also updates ktlint and the associated gradle plugin to the latest versions.

Test Steps:
1. Run usual test suite
2. Run `./gradlew ktlintCheck` and `./gradlew ktlintFormat` to ensure those work
3. Follow the steps at [prime-router/docs/getting-started/contributing.md](https://github.com/CDCgov/prime-reportstream/compare/master...platform/jimmy/11503-introduce-formatters#diff-171b35d34ae352bbe457ebac9586451090d8a09b7fc43bbbf28243b7b9199445) to set up the IDE formatter
4. Make some formatting changes, and verify that they are reformatted on save.
2. Run `./gradlew ktlintCheck` again to ensure the linter is still happy.

## Changes
This changeset is way too big to review everything. For the purposes of the review, focus on the following files:

- [.gitignore](https://github.com/CDCgov/prime-reportstream/compare/master...platform/jimmy/11503-introduce-formatters#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947)
- [prime-router/.editorconfig](https://github.com/CDCgov/prime-reportstream/compare/master...platform/jimmy/11503-introduce-formatters#diff-686e7830a3adb458e3770e566a37af3ef30d59404db575aeac8f789b0a542f28)
- [prime-router/.idea/codeStyles/Project.xml](https://github.com/CDCgov/prime-reportstream/compare/master...platform/jimmy/11503-introduce-formatters#diff-dcde54982a6d3943c7a9de27dc7923b3830183b2a77904e080208ff07acc25c2)
- [prime-router/.idea/codeStyles/codeStyleConfig.xml](https://github.com/CDCgov/prime-reportstream/compare/master...platform/jimmy/11503-introduce-formatters#diff-fd5d69207d6846211bbe818937c25a2a0b331dfbb0fb37f642fb22d23f485fd3)
- [prime-router/build.gradle.kts](https://github.com/CDCgov/prime-reportstream/compare/master...platform/jimmy/11503-introduce-formatters#diff-068a6d1fb39db0c1087c194868d0180c7d7c48bad67e3c0473697a27bf2bdf4d)
- [prime-router/docs/getting-started/contributing.md](https://github.com/CDCgov/prime-reportstream/compare/master...platform/jimmy/11503-introduce-formatters#diff-171b35d34ae352bbe457ebac9586451090d8a09b7fc43bbbf28243b7b9199445)

The rest of the changes are automatic format changes either made by the IDE or by `ktlintFormat`

## Checklist

### Testing
- [x] Tested locally?
- [x] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?

## Linked Issues
- Addresses #11503

## To Be Done
Optionally, stories can be added to re-enable some of the disabled linting rules and make the necessary refactors to allow that to happen. There is no urgency to that, so I have opted not to create a story to track it, but I can if it would be useful.

2023-10-11 01:15 UTC, jimmyfagan commented on prime-router/src/testIntegration/kotlin/datatests/mappinginventory/nte/NTETests.kt
@mkalish I could probably disable the rule that necessitated this change, but the kotlin [coding conventions](https://kotlinlang.org/docs/coding-conventions.html#naming-rules) say not to use underscores in package names and also discourage multi-word package names altogether. Does this change seem okay?

2023-10-12 14:19 UTC, arnejduranovic requested changes
This appears to work for me except for reformatting on file save, any tips there? (I followed the instructions included in the change set and my settings were already correct).

Otherwise, I can hit `⌘Сmd + ⌥Opt + L` to force the IDE to format (tested with kotlin and fhir files). `./gradlew ktlinkformat`also reformats the code where possible and generates a list of errors where it can't. I wen't through https://pinterest.github.io/ktlint/1.0.0/rules/standard/ and modified code to violate some of the non-ignored rules and verified ktlintcheck/ktlintformat can fix or catch those.

Requesting changes for the one main comment I had, which is to make ktlintformat runnable without having to have the DB up.

2023-10-13 15:43 UTC, jimmyfagan commented
Ready for re-review, and up-to-date with `master`.

2023-10-16 20:40 UTC, arnejduranovic approved these changes

2023-10-17 03:43 UTC, merged