11267 - removal of legacy pages
CDCgov/prime-reportstream pull request #11736
Opened 2023-10-11 16:19 UTC by penny-lischer

This PR ...

Is a catch all for all the work needed to deprecate and archive the legacy pages/links

Test Steps:
1. Log into RS
2. Make sure all pages and links in the site are functioning correctly.

## Changes
- Removed obsolete pages
- Updated urls to fit with the new redesign

## Checklist

### Testing
- [ ] Tested locally?
- [ ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] (For Changes to /frontend-react/...) Ran `npm run lint:write`? 
- [ ] Added tests?

## Linked Issues
- Fixes #11267

2023-10-11 21:13 UTC, audreykwr commented
AMAZING

- [ ] I think there's an old link hiding in [release notes ](https://pdhstagingpublictrial01.z13.web.core.windows.net/about/release-notes)for the API guide mentioned in July and June. I'm not going to care about all of those being right because some are pretty old updates, but July was the most recent month we published (ha) and has the old API guide link
- [ ] It looks like maybe the [old FAQ page](https://pdhstagingpublictrial01.z13.web.core.windows.net/support/faq) still exists, though I don't think it is linked anywhere so I wasn't sure if you left it for a reason.

2023-10-12 16:31 UTC, audreykwr approved these changes

2023-10-16 16:48 UTC, jpandersen87 requested changes

2023-10-16 18:33 UTC, penny-lischer commented on frontend-react/src/content/developer-resources/reportstream-api/ReportStreamApi.mdx
> +    ## <a href="frontend-react/src/content/developer-resources/reportstream-api/ReportStreamApi.mdx#about-our-api" className="usa-link usa-link--unstyled">About our API</a>
Good catch!

2023-10-16 18:38 UTC, jpandersen87 approved these changes

2023-10-17 22:26 UTC, merged