ID Mapping
CDCgov/prime-reportstream pull request #12237
Opened 2023-11-14 16:39 UTC by brick-green

This PR 

Test Steps:
1. compare mapping inventory:
  - [ID[Coding]](https://docs.google.com/spreadsheets/d/1DR9Rw8yw4F4RhbpHd0RE9ng-KLTb81RmuTOxTgVcaVc/edit#gid=0)
  - [ID[CodeableConcept-UniversalID]](https://docs.google.com/spreadsheets/d/1YnP5iXEswInGxwYcRjg81HU4ACsjRJPpQVfOzwVRdIg/edit#gid=0)
  - [ID[CodeableConcept]](https://docs.google.com/spreadsheets/d/1lKNOp9adRZq86xYTl1U_VtsIr4qTUmETR2sU3S9Ie8M/edit#gid=0)
2. Run Integration tests

## Linked Issues
- #11663

2023-11-14 18:17 UTC, arnejduranovic requested changes

2023-11-14 19:17 UTC, brick-green commented on prime-router/metadata/fhir_mapping/hl7/datatypes/ID/Coding.yml
> +code:
I agree, I'll move the logic over to encounter

2023-11-15 15:33 UTC, brick-green commented on prime-router/metadata/fhir_mapping/hl7/resource/Encounter.yml
> +            code: true
oh dang, that's a typo. Both ways work but I'll take out the string type on false. The default is string so it doesn't need to be declared.

2023-11-16 21:44 UTC, brick-green commented
@arnejduranovic In the end I removed the ID to Coding mapping in favor of inline on Encounter. The hapi library has code that filters out Coding in Meta fields when Code and System are missing. So instead I opted to convert the value if possible according to the table for PV2.22 and if it could not be converted just use the original value. On the FHIR to HL7 side the valueSet code maps the value back to Y/N. For unknown values the code will use the value from the FHIR.

2023-11-17 16:34 UTC, arnejduranovic approved these changes

2023-11-20 20:06 UTC, merged