Engagement/jgilmore/9083 ar onboarding
CDCgov/prime-reportstream pull request #12342
Opened 2023-11-21 00:38 UTC by GilmoreA6

This PR ...

**If you are suggesting a fix for a currently exploitable issue, please disclose the issue to the prime-reportstream team directly outside of GitHub instead of filing a PR, so we may immediately patch the affected systems before a disclosure. See [SECURITY.md/Reporting a Vulnerability](https://github.com/CDCgov/prime-reportstream/blob/master/SECURITY.md#reporting-a-vulnerability) for more information.**

Test Steps:
1. run ./gradlew clean package
2. run docker compose up
3. run ./prime test
4. Add settings from prime-router/settings/staging/0159-AR-onboarding.yml to local organizations.yml file and run ./gradlew reloadSettings
5. Use provided postman collection to send test message to mock AR SOAP endpoint
[AR Testing.postman_collection.json](https://github.com/CDCgov/prime-reportstream/files/13420552/AR.Testing.postman_collection.json)
6. Verify that you receive HTTP "200" response from mock endpoint
7. Verify that message is received in castlemock folder

## Changes
- *Update SOAP Serializer to work for both Soap ver 1.1 and1.2*
- *Update SOAP Transport to allow for SOAP ver. 1.1 and ver 1.2*
- *Add Soap Serializer Tests*
- *Add mock SOAP1.2 endpoint for AR to CastleMock*
- *Add AR settings for staging and prod*
- *Update credentials to allow SOAPTransport to use jks for certificate auth*

## Checklist

### Testing
- [x ] Tested locally?
- [x ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [x ] Added tests?

### Process
- [ ] Are there licensing issues with any new dependencies introduced?
- [ ] Includes a summary of what a code reviewer should test/verify?
- [ ] Updated the release notes?
- [ ] Database changes are submitted as a separate PR?
- [ ] DevOps team has been notified if PR requires ops support?

## Linked Issues
- Fixes #11138 
- Fixes #9766 
- Fixes #9083
- Fixes #9764

2023-11-22 15:06 UTC, victor-chaparro requested changes
Just added one minor comment. What are the files under `.environment/soap_service` used for? Are those auto generated, and do we have to create these files for every receiver using SOAP?

2023-11-27 05:27 UTC, GilmoreA6 commented on prime-router/src/main/kotlin/serializers/SoapSerializer.kt
> +                    xmlGen.writeObjectFieldStart("$soapNamespaceAlias:Body")
Done, extracted the soap envelope and soap12 header logic into separate functions.

2023-11-27 05:28 UTC, GilmoreA6 commented
> Just added one minor comment. What are the files under `.environment/soap_service` used for? Are those auto generated, and do we have to create these files for every receiver using SOAP?

These are created by castle mock when you feed it a WSDL file. They just allow for an easy way to mock the endpoint.

2023-11-27 21:00 UTC, snesm approved these changes

2023-11-27 21:15 UTC, merged