11443: split batch function into universal and covid
CDCgov/prime-reportstream pull request #12441
Opened 2023-11-29 21:40 UTC by jalbinson

This PR splits the batch function into seperate Covid and Universal pipeline functions. It also seperates out the batch queue into seperate Covid and Universal pipeline queues.

It intentionally leaves existing functionality so we may churn through the existing queue once this is deployed. The deprecated batch queue and function may be safely removed after the next deploy.

Test Steps:
1. ./gradlew test
2. ./gradlew testIntegration

## Changes
- Moved batching code into a new package
- Split batch function into 2 new functions and a deprecated existing function
- Update queuing code to accept a new `queueName` parameter decoupled from the `Event` code.
- Updated tests to handle new classes

## Checklist

### Testing
- [ ] Tested locally?
- [ ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] Added tests?

## Linked Issues
- Fixes #11443

## To Be Done
-TODO: write followup ticket to remove deprecated code post deploy

2023-11-29 22:50 UTC, mkalish reviewed
Few small nits, but looks great!

I'll pull this down and test tomorrow morning.

2023-11-29 22:50 UTC, mkalish commented on prime-router/src/test/kotlin/azure/batch/UniversalBatchFunctionTests.kt
Should we add some tests to cover the covid batch functino?

2023-11-29 22:50 UTC, mkalish commented on prime-router/src/main/kotlin/azure/batch/CovidBatchFunction.kt
Nit: for the follow up maybe consider doing a git mv of `DeprecatedBatchFunction` to this one?  Mostly thinking of keeping the git history

2023-11-30 14:19 UTC, mkalish requested changes
Approval was preemptive.

Looks like at least one of the names for the new queues are invalid.

```
[2023-11-30T14:19:00.047Z] com.azure.storage.queue.models.QueueStorageException: Status code 400, "<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
[2023-11-30T14:19:00.047Z] <Error>
[2023-11-30T14:19:00.047Z]   <Code>InvalidResourceName</Code>
[2023-11-30T14:19:00.047Z]   <Message>The specifed resource name contains invalid characters.
[2023-11-30T14:19:00.047Z] RequestId:9e442850-e4f4-4a41-878a-9b08916cf72b
[2023-11-30T14:19:00.047Z] Time:2023-11-30T14:19:00.045Z</Message>
[2023-11-30T14:19:00.047Z] </Error>"
```

2023-11-30 14:26 UTC, jalbinson commented on prime-router/src/test/kotlin/azure/batch/UniversalBatchFunctionTests.kt
can't hurt. I didn't add them in on first pass because there weren't any to begin with.

2023-11-30 16:11 UTC, jalbinson commented on prime-router/src/main/kotlin/azure/batch/CovidBatchFunction.kt
I just tried to fix this but git is smartly considering the file with the least amount of changes the "moved" one and the other 2 files as the new ones.

2023-12-01 21:35 UTC, merged