Updating REST Transport Documentation
CDCgov/prime-reportstream pull request #12686
Opened 2023-12-19 13:51 UTC by oslynn

This PR updated the REST Transport Documentation to reflect the new modified REST Transport

Test Steps:
1. *Include steps to test these changes*

## Changes
- *Include a comprehensive list of changes in this PR*
- *(For web UI changes) Include screenshots/video of changes*

## Checklist

### Testing
- [ ] Tested locally?
- [ ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] (For Changes to /frontend-react/...) Ran `npm run lint:write`? 
- [ ] Added tests?

### Process
- [ ] Are there licensing issues with any new dependencies introduced?
- [ ] Includes a summary of what a code reviewer should test/verify?
- [ ] Updated the release notes?
- [ ] Database changes are submitted as a separate PR?
- [ ] DevOps team has been notified if PR requires ops support?

## Linked Issues
- Fixes #issue
- https://app.zenhub.com/workspaces/engagement-6166edbd409257001e09f1b2/issues/gh/cdcgov/prime-reportstream/12680

## To Be Done
*Create GitHub issues to track the work remaining, if any*
- #issue

## Specific Security-related subjects a reviewer should pay specific attention to
- Does this PR introduce new endpoints?
    - new endpoint A
    - new endpoint B
- Does this PR include changes in authentication and/or authorization of existing endpoints?
- Does this change introduce new dependencies that need vetting?
- Does this change require changes to our infrastructure?
- Does logging contain sensitive data?
- Does this PR include or remove any sensitive information itself?

If you answered '_yes_' to any of the questions above, conduct a detailed Review that addresses at least:

- What are the potential security threats and mitigations? Please list the _STRIDE_ threats and how they are mitigated
    - **S**poofing (faking authenticity)
        - Threat _T_, which could be achieved by _A_, is mitigated by _M_
    - **T**ampering (influence or sabotage the integrity of information, data, or system)
    - **R**epudiation (the ability to dispute the origin or originator of an action)
    - **I**nformation disclosure (data made available to entities who should not have it)
    - **D**enial of service (make a resource unavailable)
    - **E**levation of Privilege (reduce restrictions that apply or gain privileges one should not have)
- Have you ensured logging does not contain sensitive data?
- Have you received any additional approvals needed for this change?

2023-12-21 15:43 UTC, adegolier commented on prime-router/docs/onboarding-users/transport/rest.md
> +            "email/password" - Authenticates with json body { "email": "<username>", "password": "<password>" }
```suggestion
            "email/password" - Authenticates with json body { "email": "<email>", "password": "<password>" }
```

2023-12-21 15:44 UTC, adegolier commented on prime-router/docs/onboarding-users/transport/rest.md
> +            "Subscription" - Given to us by STLT (It is as plublic key and not secrete)
```suggestion
            "Subscription" - Given to us by STLT (It is as public key and not secret)
```

2023-12-21 15:45 UTC, adegolier commented on prime-router/docs/onboarding-users/transport/rest.md
> +            "Subscription" - Given to us by STLT (It is as plublic key and not secrete)
```suggestion
            "Subscription" - Given to us by STLT (It is as public key and not secret)
```

2023-12-21 15:45 UTC, adegolier commented on prime-router/docs/onboarding-users/transport/rest.md
> +            "payload" - Set "multipart/form-data" key value to payload (uses by NY-PHD)
```suggestion
            "payload" - Set "multipart/form-data" key value to payload (used by NY-PHD)
```

2023-12-21 15:46 UTC, adegolier commented on prime-router/docs/onboarding-users/transport/rest.md
> +            "files" - Set "multipart/form-data" key value to file (uses by LA-PHL/Natus).
```suggestion
            "files" - Set "multipart/form-data" key value to file (used by LA-PHL/Natus).
```

2023-12-21 15:48 UTC, adegolier approved these changes
A few minor typo corrections, but otherwise lgtm

2023-12-28 10:10 UTC, oslynn commented on prime-router/docs/onboarding-users/transport/rest.md
> +            "email/password" - Authenticates with json body { "email": "<username>", "password": "<password>" }
Thank you @adegolier

2024-01-10 14:55 UTC, victor-chaparro requested changes

2024-01-10 14:55 UTC, victor-chaparro commented on prime-router/docs/onboarding-users/transport/rest.md
> +        . File-Name: Set customer message's file name.  If the name includes substring "withdate", it will include datetime with the name.
Is this still needed?

2024-01-10 21:13 UTC, oslynn commented
Used the existing Report.formFileName to generate the filename.  Therefore, we don't need to update the document.

2024-01-10 21:13 UTC, closed without merging