1349 Added Care Evolution sender and schema
CDCgov/prime-reportstream pull request #1351
Opened 2021-06-21 15:35 UTC by carlosfelix2

This PR adds Care Evolution as a sender.

## Changes
- Added Care Evolution as a sender
- Create schema for Care Evolution

## Checklist

### Testing
- [ ] Tested locally?
- [ ] Ran `quickTest all`?
- [ ] Ran `./prime test` against local Docker ReportStream container?
- [ ] Downloaded a file from `http://localhost:7071/api/download`?
- [ ] Added tests?

### Security
- [ ] Did you check for sensitive data, and remove any? 
- [ ] Does logging contain sensitive data?  
- [ ] Are additional approvals needed for this change?
- [ ] Are there potential vulnerabilities or licensing issues with any new dependencies introduced?

### Process
- [ ] Includes a summary of what a code reviewer should verify?
- [ ] Updated the release notes?
- [ ] Database changes are submitted as a separate PR?
- [ ] DevOps team has been notified if PR requires ops support?

## Security
*List potential security threats and mitigations in the PR*

## Fixes
*List GitHub issues this PR fixes*
- #issue

## To Be Done
*Create GitHub issues to track the work remaining, if any*
- #issue

2021-06-21 17:00 UTC, jimduff-usds requested changes
Carlos, 

Are you able to create fake data using the new schema?
Also, note my change needed for organizations-test.yml

2021-06-21 17:08 UTC, carlosfelix2 commented
> Carlos,
> 
> Are you able to create fake data using the new schema?
> Also, note my change needed for organizations-test.yml

Yes, I can create fake data with no issues.  The extends works if that is what you are asking.

2021-06-21 17:19 UTC, carlosfelix2 commented on prime-router/settings/organizations-test.yml
>        format: CSV
Ok.  I understand why it is used.  Check the changes again and see if that looks right,  Thx.

2021-06-22 09:39 UTC, jimduff-usds approved these changes

2021-06-22 09:40 UTC, merged