Massive dependabot upgrade
CDCgov/prime-reportstream pull request #13596
Opened 2024-03-06 06:19 UTC by thetaurean

This PR resolves a large collection of dependabots, 29 in total.

Test Steps:
1. Run test suites

## Changes
- Dependencies updated (see commit messages or linked issues for which)

## Checklist

### Testing
- [x] Tested locally?
- [x] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?

## Linked Issues
- Fixes #13566
- Fixes #13565
- Fixes #13549
- Fixes #13548
- Fixes #13547
- Fixes #13490
- Fixes #13489
- Fixes #13460
- Fixes #13459
- Fixes #13418
- Fixes #13417
- Fixes #13416
- Fixes #13415
- Fixes #13337
- Fixes #13335
- Fixes #13332
- Fixes #13243
- Fixes #13148
- Fixes #13091
- Fixes #13085
- Fixes #13056
- Fixes #12795
- Fixes #12794
- Fixes #12743
- Fixes #12739
- Fixes #12489
- Fixes #12391
- Fixes #12387
- Fixes #12313

2024-03-06 13:50 UTC, snesm commented
@thetaurean Please add https://github.com/CDCgov/prime-reportstream/pull/13426

2024-03-06 18:42 UTC, snesm requested changes
please add https://github.com/CDCgov/prime-reportstream/pull/13426

2024-03-07 17:27 UTC, arnejduranovic approved these changes

2024-03-13 12:22 UTC, snesm approved these changes

2024-03-13 14:57 UTC, merged