Platform/7656/clean mime
CDCgov/prime-reportstream pull request #14950
Opened 2024-07-01 00:26 UTC by david-navapbc

This PR ...

Test Steps:
1. build the project and run the tests. 

## Changes
* MIME types are not in a new enum class MimeFormat
* where possible, we're using MIME constants from fhir library we're already using
* everything looking for Sender.Format or Report.Format now points to MimeFormat

## Checklist

### Testing
- [ x] Tested locally?
- [x ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] (For Changes to /frontend-react/...) Ran `npm run lint:write`? 
- [ ] Added tests?

### Process
- [ ] Are there licensing issues with any new dependencies introduced?
- [ ] Includes a summary of what a code reviewer should test/verify?
- [ ] Updated the release notes?
- [ ] Database changes are submitted as a separate PR?
- [ ] DevOps team has been notified if PR requires ops support?

## Linked Issues
- Fixes #issue

## To Be Done
*Create GitHub issues to track the work remaining, if any*
- #issue

## Specific Security-related subjects a reviewer should pay specific attention to
- Does this PR introduce new endpoints?
    - new endpoint A
    - new endpoint B
- Does this PR include changes in authentication and/or authorization of existing endpoints?
- Does this change introduce new dependencies that need vetting?
- Does this change require changes to our infrastructure?
- Does logging contain sensitive data?
- Does this PR include or remove any sensitive information itself?

If you answered '_yes_' to any of the questions above, conduct a detailed Review that addresses at least:

- What are the potential security threats and mitigations? Please list the _STRIDE_ threats and how they are mitigated
    - **S**poofing (faking authenticity)
        - Threat _T_, which could be achieved by _A_, is mitigated by _M_
    - **T**ampering (influence or sabotage the integrity of information, data, or system)
    - **R**epudiation (the ability to dispute the origin or originator of an action)
    - **I**nformation disclosure (data made available to entities who should not have it)
    - **D**enial of service (make a resource unavailable)
    - **E**levation of Privilege (reduce restrictions that apply or gain privileges one should not have)
- Have you ensured logging does not contain sensitive data?
- Have you received any additional approvals needed for this change?

2024-07-02 17:07 UTC, thetaurean requested changes
Changes look great! Boy was that mess getting out of hand.

Some minor comments in files and some small fixes needed:
- Props for updating docs!
- Please fix integration tests: looks like some references need updating (`TestIntegration` gradle task)
- Please finish PR template:
  - update "This PR..." text
  - add Fixes #ticketnumber 
    - Fixes #7656 
  - remove security section if not applicable
- For future branches please avoid creating per-ticket branches in `platform/`. Highly suggest naming convention: `platform/[githubname]/[ticket-number]-some-text-here`

2024-07-02 18:03 UTC, david-navapbc commented on prime-router/src/main/kotlin/Sender.kt
> +//    }
oops - good catch! I will remove

2024-07-02 18:07 UTC, david-navapbc commented on prime-router/src/main/kotlin/Sender.kt
> -        HL7_BATCH("application/hl7-v2"),
I don't think so? The same information is being stored in the db regardless of whether or not the legacy Sender.Format was used or the new Mime.Format.

2024-07-03 02:47 UTC, thetaurean commented on prime-router/src/main/kotlin/Sender.kt
> -        HL7_BATCH("application/hl7-v2"),
The enum vals get serialized to int in the db, so I believe:

Sender.Format.HL7_BATCH would become a 4
Mime.Format.HL7_BATCH would become a 5

These could be off by 1 I can't remember if Enum->Int starts at 1 or 0.

2024-07-04 20:36 UTC, david-navapbc commented on prime-router/src/main/kotlin/Sender.kt
> -        HL7_BATCH("application/hl7-v2"),
all of the tests are passing. is there a particular issue you are concerned about that's not covered by the test rig?

2024-07-04 20:39 UTC, david-navapbc commented
> Changes look great! Boy was that mess getting out of hand.
> 
> Some minor comments in files and some small fixes needed:
> 
>     * Props for updating docs!
> 
>     * Please fix integration tests: looks like some references need updating (`TestIntegration` gradle task)
> 
>     * Please finish PR template:
>       
>       * update "This PR..." text
>       * add Fixes #ticketnumber
>         
>         * Fixes [Clean up enumerations with duplicate mime types #7656](https://github.com/CDCgov/prime-reportstream/issues/7656)
>       * remove security section if not applicable
> 
>     * For future branches please avoid creating per-ticket branches in `platform/`. Highly suggest naming convention: `platform/[githubname]/[ticket-number]-some-text-here` e.g. `platform/thetaurean/1234-do-it`

done and done.

2024-07-08 18:31 UTC, thetaurean approved these changes
👍

2024-07-09 15:32 UTC, arnejduranovic approved these changes
Changes look good. Good job getting rid of the redundant code! Small nit: Update PR description to have the "Fixes" in the proper section below.

2024-07-10 00:00 UTC, merged