Experience/15059/smoke GitHub action
CDCgov/prime-reportstream pull request #15293
Opened 2024-07-22 18:24 UTC by penny-lischer

This PR ...

Added github action workflow for frontend smoke tests to be run against live data.

Test Steps:

Run the Start Frontend Smoke Tests workflow.
You should be prompted to select your admin un/pw for such environment.

## Changes

## Checklist

### Testing
- [ ] Tested locally?
- [ ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] (For Changes to /frontend-react/...) Ran `npm run lint:write`? 
- [ ] Added tests?

## Linked Issues
- Fixes #15059

2024-07-22 19:35 UTC, jeremy-page approved these changes

2024-07-22 19:39 UTC, snesm requested changes
Looks like there are 10 frontend files with format changes attached.

Please remove.

2024-07-22 20:02 UTC, penny-lischer commented
> Looks like there are 10 frontend files with format changes attached.
> 
> Please remove.

These are linting updates and will get resolved when updated with master since there is another PR that resolves them.

2024-07-22 20:37 UTC, jpandersen87 approved these changes

2024-07-23 12:13 UTC, snesm approved these changes

2024-07-23 16:30 UTC, merged