Added ability to send reports using PUT
CDCgov/prime-reportstream pull request #15528
Opened 2024-08-06 22:46 UTC by victor-chaparro

This PR adds the ability to send reports using PUT through the REST transport and also sets the accessToken if provided in the credential.
Minnesota's REST API only accepts reports be sent to them using PUT. The `transport.headers.method` setting must be set to `PUT` so that the REST transport can configure the HTTP client to send via PUT, otherwise it will use POST by default.

**If you are suggesting a fix for a currently exploitable issue, please disclose the issue to the prime-reportstream team directly outside of GitHub instead of filing a PR, so we may immediately patch the affected systems before a disclosure. See [SECURITY.md/Reporting a Vulnerability](https://github.com/CDCgov/prime-reportstream/blob/master/SECURITY.md#reporting-a-vulnerability) for more information.**

Test Steps:
1. Run `./prime multiple-settings set --input ./settings/STLTs/MN/mn-doh.yml`
2. Send test report routed to MN
3. Verify the report gets sent to MN

## Changes
- Added ability to specify REST method inside transport.headers

## Checklist

### Testing
- [x] Tested locally?
- [x] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] (For Changes to /frontend-react/...) Ran `npm run lint:write`? 
- [ ] Added tests?

## Linked Issues
- Fixes #14696

2024-08-07 13:06 UTC, JessicaWNava approved these changes
Couple of minor changes. Mostly I need to know how to verify that the message sent to them. I didn't see any errors when I sent it, but is there another way to verify?

2024-08-07 13:07 UTC, JessicaWNava requested changes
Oops meant to request changes

2024-08-07 14:51 UTC, JessicaWNava approved these changes
Changes good, just waiting on instructions to figure out how to verify that the message actually sent.

2024-08-07 15:19 UTC, JessicaWNava commented
When I tested this I did not see a send_error action in the table. Seems to be stuck on waiting to deliver despite the numberPerDay being set to 1440

2024-08-08 16:13 UTC, GilmoreA6 commented on prime-router/src/main/kotlin/transport/RESTTransport.kt
> +                    build(logger, headers, message, fileName, boundary, reportCreateDate)
can we add a test to cover this logic split here?

2024-08-09 22:26 UTC, GilmoreA6 approved these changes

2024-08-14 20:33 UTC, merged