Resolve open backend dependabots
CDCgov/prime-reportstream pull request #15903
Opened 2024-09-17 16:53 UTC by thetaurean

This PR resolves a collection of dependabots, 23 in total.

Test Steps:
1. Run test suites

## Changes
- Dependencies updated (see commit messages or linked issues for which)

## Checklist

### Testing
- [x] Tested locally?
- [x] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?

## Linked Issues
- Fixes #15892
- Fixes #15891
- Fixes #15889
- Fixes #15888
- Fixes #15887
- Fixes #15886
- Fixes #15885
- Fixes #15813
- Fixes #15811
- Fixes #15754
- Fixes #15753
- Fixes #15750
- Fixes #15749
- Fixes #15698
- Fixes #15697
- Fixes #15696
- Fixes #15695
- Fixes #15694
- Fixes #15693
- Fixes #15691
- Fixes #15641
- Fixes #15640
- Fixes #15557

2024-09-18 12:20 UTC, snesm requested changes

2024-09-18 12:20 UTC, snesm commented on submissions/build.gradle.kts
>      id("org.springframework.boot") version "3.3.2"
3.3.3 is a security fix (https://github.com/CDCgov/prime-reportstream/pull/15695).  We should probably take /submissions PRs out of this and handle them separately.

2024-09-19 15:57 UTC, snesm commented on submissions/build.gradle.kts
>      id("org.springframework.boot") version "3.3.2"
We may want to split out /shared PRs as well.

2024-09-24 14:25 UTC, arnejduranovic approved these changes

2024-09-24 17:20 UTC, merged