Check submission table when computing submission history
CDCgov/prime-reportstream pull request #16200
Opened 2024-10-11 14:46 UTC by thetaurean

This PR updates the submission history code to check the new submission table in azure storage when a submissionId is not found in the primary postgres database.

Test Steps:
1. Run integration test suite

## Changes
- Updated submission history code to check azure storage table
- Added timestamp field and JSON annotations to shared `Submission` class

## Checklist

### Testing
- [x] Tested locally?
- [x] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [x] Added tests?

## Linked Issues
- Fixes #15822

2024-10-11 17:11 UTC, david-navapbc requested changes
there is a test failure when I run this on my workstation that does not happen when I do the same in master branch.

```java.lang.NullPointerException: getenv(...) must not be null
      at gov.cdc.prime.router.history.azure.DeliveryFunctionTests.test delivery details(DeliveryFunctionTests.kt:465)
```

2024-10-11 18:16 UTC, david-navapbc approved these changes
tests now pass for me locally - nice work!

2024-10-15 14:49 UTC, thetaurean commented on prime-router/src/main/kotlin/history/azure/ReportFileFunction.kt
> +                HttpUtilities.notFoundResponse(request, ex.message)
I agree with you however this was pre-existing code so I didn't feel comfortable changing it.

For the most part this is catching exceptions that we throw, so the error messages are things we set. Though `IllegalStateException` is pretty broad and could probably occur unexpectedly.

2024-10-17 20:54 UTC, arnejduranovic approved these changes
Changes look good. In the background will work to put up a follow-up PR to use dependency injection with SubmissionTableService

2024-10-17 21:36 UTC, merged