#16730 timezone enrichment documentation
CDCgov/prime-reportstream pull request #16779
Opened 2024-12-11 16:19 UTC by the-andrew

Update docs to mentions changes for time zone conversion translation to use enrichment schema

**If you are suggesting a fix for a currently exploitable issue, please disclose the issue to the prime-reportstream team directly outside of GitHub instead of filing a PR, so we may immediately patch the affected systems before a disclosure. See [SECURITY.md/Reporting a Vulnerability](https://github.com/CDCgov/prime-reportstream/blob/main/SECURITY.md#reporting-a-vulnerability) for more information.**

Test Steps:
1. *Include steps to test these changes*

## Changes
- *Include a comprehensive list of changes in this PR*
- *(For web UI changes) Include screenshots/video of changes*

## Checklist

### Testing
- [ ] Tested locally?
- [ ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] (For Changes to /frontend-react/...) Ran `npm run lint:write`?
- [ ] Added tests?

### Process
- [ ] Are there licensing issues with any new dependencies introduced?
- [ ] Includes a summary of what a code reviewer should test/verify?
- [ ] Updated the release notes?
- [ ] Database changes are submitted as a separate PR?
- [ ] DevOps team has been notified if PR requires ops support?

## Linked Issues
- Fixes #issue

## To Be Done
*Create GitHub issues to track the work remaining, if any*
- #issue

## Specific Security-related subjects a reviewer should pay specific attention to
- Does this PR introduce new endpoints?
    - new endpoint A
    - new endpoint B
- Does this PR include changes in authentication and/or authorization of existing endpoints?
- Does this change introduce new dependencies that need vetting?
- Does this change require changes to our infrastructure?
- Does logging contain sensitive data?
- Does this PR include or remove any sensitive information itself?

If you answered '_yes_' to any of the questions above, conduct a detailed Review that addresses at least:

- What are the potential security threats and mitigations? Please list the _STRIDE_ threats and how they are mitigated
    - **S**poofing (faking authenticity)
        - Threat _T_, which could be achieved by _A_, is mitigated by _M_
    - **T**ampering (influence or sabotage the integrity of information, data, or system)
    - **R**epudiation (the ability to dispute the origin or originator of an action)
    - **I**nformation disclosure (data made available to entities who should not have it)
    - **D**enial of service (make a resource unavailable)
    - **E**levation of Privilege (reduce restrictions that apply or gain privileges one should not have)
- Have you ensured logging does not contain sensitive data?
- Have you received any additional approvals needed for this change?

2024-12-11 16:35 UTC, victor-chaparro requested changes
Looks good, just had one minor change. We shouldn't reference master anymore. I think I may have sent you that link, so that's my bad.

2024-12-11 16:35 UTC, victor-chaparro commented on prime-router/docs/onboarding-users/migrating-receivers.md
> +* `convertDateTimesToReceiverLocalTime` This setting is no longer able to be used directly. If this setting is present, it should be set to `false`. To enable similar functionality to convert datetim
```suggestion
* `convertDateTimesToReceiverLocalTime` This setting is no longer able to be used directly. If this setting is present, it should be set to `false`. To enable similar functionality to convert datetimes instead, an enrichment schema can be added under the `enrichmentSchemaNames` list. See also: [Translate#extending-schemas](https://github.com/CDCgov/prime-reportstream/blob/main/prime-router/docs/universal-pipeline/translate.md#extending-schemas)
```

2024-12-11 16:45 UTC, the-andrew commented
> Looks good, just had one minor change. We shouldn't reference master anymore. I think I may have sent you that link, so that's my bad.

Oh, I've been working off main, but my browser bookmark for the top level repo still goes to master. I can update the links.

2024-12-17 15:02 UTC, oslynn approved these changes

2024-12-17 20:40 UTC, the-andrew commented on prime-router/docs/onboarding-users/migrating-receivers.md
>  ```
Added

2024-12-17 20:49 UTC, lucero-v approved these changes
Looks good! Thank you for testing those settings with me.

2024-12-17 21:12 UTC, victor-chaparro approved these changes

2024-12-17 21:50 UTC, merged