[16141] Implement ReceiverEnrichment Function
CDCgov/prime-reportstream pull request #16854
Opened 2024-12-19 14:50 UTC by wcutshall

This PR ...

**If you are suggesting a fix for a currently exploitable issue, please disclose the issue to the prime-reportstream team directly outside of GitHub instead of filing a PR, so we may immediately patch the affected systems before a disclosure. See [SECURITY.md/Reporting a Vulnerability](https://github.com/CDCgov/prime-reportstream/blob/main/SECURITY.md#reporting-a-vulnerability) for more information.**

Test Steps:
1. *Include steps to test these changes*

## Changes
- *Include a comprehensive list of changes in this PR*
- *(For web UI changes) Include screenshots/video of changes*

## Checklist

### Testing
- [ ] Tested locally?
- [ ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] (For Changes to /frontend-react/...) Ran `npm run lint:write`?
- [ ] Added tests?

### Process
- [ ] Are there licensing issues with any new dependencies introduced?
- [ ] Includes a summary of what a code reviewer should test/verify?
- [ ] Updated the release notes?
- [ ] Database changes are submitted as a separate PR?
- [ ] DevOps team has been notified if PR requires ops support?

## Linked Issues
- Fixes #issue

## To Be Done
*Create GitHub issues to track the work remaining, if any*
- #issue

## Specific Security-related subjects a reviewer should pay specific attention to
- Does this PR introduce new endpoints?
    - new endpoint A
    - new endpoint B
- Does this PR include changes in authentication and/or authorization of existing endpoints?
- Does this change introduce new dependencies that need vetting?
- Does this change require changes to our infrastructure?
- Does logging contain sensitive data?
- Does this PR include or remove any sensitive information itself?

If you answered '_yes_' to any of the questions above, conduct a detailed Review that addresses at least:

- What are the potential security threats and mitigations? Please list the _STRIDE_ threats and how they are mitigated
    - **S**poofing (faking authenticity)
        - Threat _T_, which could be achieved by _A_, is mitigated by _M_
    - **T**ampering (influence or sabotage the integrity of information, data, or system)
    - **R**epudiation (the ability to dispute the origin or originator of an action)
    - **I**nformation disclosure (data made available to entities who should not have it)
    - **D**enial of service (make a resource unavailable)
    - **E**levation of Privilege (reduce restrictions that apply or gain privileges one should not have)
- Have you ensured logging does not contain sensitive data?
- Have you received any additional approvals needed for this change?

2025-01-28 01:28 UTC, JFisk42 reviewed
The new receiver enrichment is looking good! I mostly had some nitpicks to offer.

I ran the manual test steps locally and was able to verify them with a little adjustment (see fhir-message-header-sample.yml for details). 

One thing to note is that I had to do some weird steps to run RS due to the db migrations. AFAIK this is the first time I've really had to update my local setup to reflect db changes so I may be ignorant of how to do this properly.

My command order to run these changes:
``` 
docker-compose -f docker-compose.build.yml up --detach
./gradlew resetDB
./gradlew reloadTables // this is going to fail
./gradlew quickRun
./gradlew reloadTables // this is going to succeed now
./gradlew reloadSettings
```

I had to run reloadTables twice because trying to run RS without it errored out as "Unresolved reference: receiver_enrichment"
but if running reloadTables before RS is up, it will eventually error out (after affecting the changes) because the backend isn't running.

---

Testing results 

These results are with the changes detailed in fhir-message-header-sample.yml, snippets extracted for brevity.

Input HL7 sent with `development.dev-elims`:
```
MSH|^~\&|CDC PRIME - Atlanta,^2.16.840.1.114222.4.1.237821^ISO|Winchester House^05D2222542^ISO|CDPH CA REDIE^2.16.840.1.114222.4.3.3.10.1.1^ISO|CDPH_CID^2.16.840.1.114222.4.1.214104^ISO|20210803131511.0147+0000||ORU^R01^ORU_R01|1234d1d1-95fe-462c-8ac6-46728dba581c|P|2.5.1|||NE|NE|USA|UNICODE UTF-8|||PHLabReport-NoAck^ELR_Receiver^2.16.840.1.113883.9.11^ISO
SFT|Centers for Disease Control and Prevention|0.1-SNAPSHOT|PRIME Data Hub|0.1-SNAPSHOT||20210726
```

Resulting output HL7 received by `development.DEV_ENRICHMENT`:
```
MSH|^~\&|CDC PRIME - Atlanta,^2.16.840.1.114222.4.1.237821^ISO|Winchester House^05D2222542^ISO|CDPH CA REDIE^2.16.840.1.114222.4.3.3.10.1.1^ISO|CDPH_CID^2.16.840.1.114222.4.1.214104^ISO|20210803131511.0147+0000||ORU^R01^ORU_R01|1234d1d1-95fe-462c-8ac6-46728dba581c|P|2.5.1|||NE|NE|USA|UNICODE UTF-8|||PHLabReport-NoAck^ELR_Receiver^2.16.840.1.113883.9.11^ISO
SFT|Orange Software Vendor Name|0.2-YELLOW|Purple PRIME ReportStream|0.1-SNAPSHOT||20210726
```

Setup a FHIR receiver using the same enrichment:
```
    - name: DEV_ENRICHMENT_FHIR
      externalName: Enrichment Development FHIR
      organizationName: development
      topic: full-elr
      customerStatus: active
      translation:
        type: "FHIR"
      enrichmentSchemaNames: ["classpath:/metadata/fhir_transforms/receivers/fhir-message-header-sample.yml"]
```

Resulting output FHIR received by `development.DEV_ENRICHMENT_FHIR`:
``` json
{
  "resourceType": "Bundle",
  "id": "1738026051290321000.f19c5c44-bc9e-4451-9021-31a472c63311",
  "timestamp": "2021-08-03T06:15:11.015-07:00",
  "entry": [
    {
      "fullUrl": "MessageHeader/1738026051344027000.77ab067b-c8ef-4bc8-b225-d338aaa89a26",
      "resource": {
        "resourceType": "MessageHeader",
        "id": "1738026051344027000.77ab067b-c8ef-4bc8-b225-d338aaa89a26",
        "source": {
          "software": "PRIME Data Hub",
          "version": "0.1-SNAPSHOT",
          "endpoint": "urn:oid:2.16.840.1.114222.4.1.237821"
        }
      }
    },
    {
      "fullUrl": "Provenance/1738026051394889000.b3eddc01-54a4-478a-8974-09160eb98815",
      "resource": {
        "resourceType": "Provenance",
        "id": "1738026051394889000.b3eddc01-54a4-478a-8974-09160eb98815",
        "entity": [
          {
            "role": "source",
            "what": {
              "reference": "Device/1738026051396739000.581ba9b0-2d47-45c0-9ee9-92ea4301ae54"
            }
          }
        ]
      }
    },
    {
      "fullUrl": "Organization/1738026051396594000.75cda0eb-85c4-43c9-a7eb-f79c8e76750b",
      "resource": {
        "resourceType": "Organization",
        "id": "1738026051396594000.75cda0eb-85c4-43c9-a7eb-f79c8e76750b",
        "name": "Orange Software Vendor Name"
      }
    },
    {
      "fullUrl": "Device/1738026051396739000.581ba9b0-2d47-45c0-9ee9-92ea4301ae54",
      "resource": {
        "resourceType": "Device",
        "id": "1738026051396739000.581ba9b0-2d47-45c0-9ee9-92ea4301ae54",
        "extension": [
          {
            "url": "https://reportstream.cdc.gov/fhir/StructureDefinition/software-vendor-org",
            "valueReference": {
              "reference": "Organization/1738026051396594000.75cda0eb-85c4-43c9-a7eb-f79c8e76750b"
            }
          }
        ],
        "manufacturer": "Centers for Disease Control and Prevention",
        "deviceName": [
          {
            "name": "Purple PRIME ReportStream",
            "type": "manufacturer-name"
          }
        ],
        "modelNumber": "0.1-SNAPSHOT",
        "version": [
          {
            "extension": [],
            "value": "0.2-YELLOW"
          }
        ]
      }
    }
  ]
}
```

2025-01-28 01:28 UTC, JFisk42 commented on prime-router/src/main/resources/metadata/fhir_transforms/receivers/fhir-message-header-sample.yml
> +# This configuration is used to instantiate a FHIRTransformer object.
This comment looks to be in error.

2025-01-28 01:28 UTC, JFisk42 commented on prime-router/src/main/resources/metadata/fhir_transforms/receivers/fhir-message-header-sample.yml
> +  - name: software-name
Because these are the legacy transforms they won't enrich the bundle in a way that the HL7 will capture. 

I realized this while running through the test steps, I could only see `software-vendor-name` reflected in the resulting HL7. After updating this file locally to the new fhirpaths I was able to get the correct results:
``` yaml
  - name: software-name
    resource: 'Bundle.entry.resource.ofType(Provenance).where(entity.exists()).entity.what.resolve().where(extension(%`rsext-software-vendor-org`).exists())'
    bundleProperty: '%resource.deviceName.name'
    value: [ '"Purple PRIME ReportStream"' ]

  - name: software-version
    resource: 'Bundle.entry.resource.ofType(Provenance).where(entity.exists()).entity.what.resolve().where(extension(%`rsext-software-vendor-org`).exists())'
    bundleProperty: '%resource.version.value'
    value: [ '"0.2-YELLOW"' ]
```

2025-01-28 14:37 UTC, wcutshall commented on prime-router/docs/design/design/transformations.md
> +FHIR bundles are transformed (enriched) to FHIR during the [Convert](../../universal-pipeline/convert.md) and [Receiver Enrichment](../../universal-pipeline/receiver-enrichment.md) steps in the Unive
Wording is updated.

2025-01-28 14:38 UTC, wcutshall commented on prime-router/src/main/kotlin/fhirengine/engine/FHIRTranslator.kt
> +                else -> {
Re-formatted.

2025-01-28 14:38 UTC, wcutshall commented on prime-router/src/main/kotlin/fhirengine/engine/FHIRReceiverEnrichment.kt
> +                report.getItemHashForRow(1)
Leaving as is.

2025-01-28 14:38 UTC, wcutshall commented on prime-router/src/main/kotlin/fhirengine/engine/FHIRReceiverEnrichment.kt
> +    // TODO Change these to correct values.
Yup.  Removed.

2025-01-28 14:39 UTC, wcutshall commented on prime-router/src/test/kotlin/fhirengine/engine/FHIRReceiverEnrichmentTests.kt
> +    fun `fail - invalid message type`() {
Updated.

2025-01-28 14:39 UTC, wcutshall commented on prime-router/src/main/resources/metadata/fhir_transforms/receivers/fhir-message-header-sample.yml
> +# This configuration is used to instantiate a FHIRTransformer object.
Removed comment to avoid confusion.

2025-01-28 19:06 UTC, arnejduranovic requested changes
Looks great, just a few little comments. I compared the the implementation to the SRD documented here and found no deviations (besides the one listed in my comments).

https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B5EFF6D93-7CE3-4BFA-8651-E588BDD4EA44%7D&file=Universal%20Pipeline%20SRD.docx&action=default&mobileredirect=true

2025-01-28 19:06 UTC, arnejduranovic commented on prime-router/src/main/resources/db/migration/V72__add_receiver_enrichment_task.sql
> +ALTER TYPE public.task_action ADD VALUE 'receiver-enrichment' after 'destination-filter';
I know we discussed this but looking at the actual DB changes in these two migration files, I don't see why we can't make these two a separate PR, merge and deploy it, and then merge this branch?

2025-01-28 19:16 UTC, arnejduranovic commented on prime-router/src/main/kotlin/fhirengine/engine/FHIRReceiverEnrichment.kt
> +                logger.info("Applying enrichment schema $enrichmentSchemaName")
Include report id and parent report Id here maybe?

2025-01-29 01:29 UTC, wcutshall commented on prime-router/src/test/kotlin/fhirengine/azure/FHIRReceiverEnrichmentIntegrationTests.kt
> +    fun `successfully add enrichments`() {
Since nothing is to be done, please mark this resolved.

2025-01-29 01:55 UTC, wcutshall commented on prime-router/src/test/kotlin/fhirengine/azure/FHIRTranslatorIntegrationTests.kt
> +                enrichmentSchemaNames = emptyList()
Test was removed.

2025-01-29 01:56 UTC, wcutshall commented on prime-router/docs/universal-pipeline/receiver-enrichment.md
> +After the [destination filter](./destination-filter.md) step has completed, each configured receiver will receive the converted FHIR bundle for potential further enrichment.  If the specific receiver
Change applied.

2025-01-29 01:56 UTC, wcutshall commented on prime-router/src/main/kotlin/fhirengine/engine/FHIRReceiverEnrichment.kt
> +     * Accepts a [FhirReceiverEnrichmentQueueMessage] [message] and sends a report to the
Change applied.

2025-01-29 01:56 UTC, wcutshall commented on prime-router/src/main/kotlin/fhirengine/engine/FHIRReceiverEnrichment.kt
> +            eventName = ReportStreamEventName.ITEM_ROUTED,
Change applied.

2025-01-29 01:57 UTC, wcutshall commented on prime-router/src/main/kotlin/fhirengine/engine/FHIRReceiverEnrichment.kt
> +                logger.info("Applying enrichment schema $enrichmentSchemaName")
Root report id is not available within this scope.  I did add reportId.

2025-01-29 15:00 UTC, wcutshall commented on prime-router/src/main/resources/db/migration/V72__add_receiver_enrichment_task.sql
> +ALTER TYPE public.task_action ADD VALUE 'receiver-enrichment' after 'destination-filter';
Second PR is in place in case we want to do that.

2025-01-29 16:05 UTC, wcutshall commented on prime-router/src/main/resources/metadata/fhir_transforms/receivers/fhir-message-header-sample.yml
> +  - name: software-name
Updated the sample file with this info.

2025-01-29 17:14 UTC, JFisk42 approved these changes
Looking great now! 🎸 🚀 👍

2025-01-29 18:15 UTC, arnejduranovic approved these changes

2025-01-30 20:15 UTC, merged