Update the API Guide with Code mapping template & instructions
CDCgov/prime-reportstream pull request #16850
Opened 2024-12-18 19:05 UTC by etanb

Fixes #16628

2024-12-18 19:59 UTC, jillian-hammer requested changes
thanks @etanb this is looking great! a few notes:
- [ ] Step 1: Some of the text is missing the bold styling. ("Note: If you’re testing OTC data, use the [NIST HL7 General Validation Tool](https://hl7v2-gvt.nist.gov/gvt/#/home) and select **RADx MARS HL7v2** from the **Tool Scopes** dropdown. Navigate to the **Context-free** tab and select the **Onboarding** profile group. Correct any errors you receive.")
- [ ] Step 2.2: Remove period after header `Set up your file`
- [ ] Can you double check that that anchor links for the accordions is working and are unique to that accordion? For example, when I open accordion for Step 2.1, the URL changes to `developer-resources/api/getting-started#1` but that is the same URL when I open Step 3.1. and when I try to open that link in a new tab, it does not auto link to that open accordion. it just opens the page from the top.

2024-12-19 17:47 UTC, jillian-hammer commented on frontend-react/src/content/developer-resources/reportstream-api/getting-started/GettingStarted.mdx
> +select** RADx MARS HL7v2** from the **Tool Scopes** dropdown. Navigate to the **Context-free** tab and select the **Onboarding** profile group.
- [ ]  fix bold styling (screenshot from preview link below)
<img width="258" alt="image" src="https://github.com/user-attachments/assets/00a728a7-7738-4b39-826f-eb70e1da3d29" />

2024-12-19 18:14 UTC, jillian-hammer approved these changes
LGTM thanks @etanb!!

2024-12-19 21:58 UTC, victor-chaparro approved these changes

2024-12-24 22:46 UTC, merged