Flexion/jgilmore/update blob storage transport filenames
CDCgov/prime-reportstream pull request #16920
Opened 2024-12-27 19:15 UTC by GilmoreA6

This PR ...

**If you are suggesting a fix for a currently exploitable issue, please disclose the issue to the prime-reportstream team directly outside of GitHub instead of filing a PR, so we may immediately patch the affected systems before a disclosure. See [SECURITY.md/Reporting a Vulnerability](https://github.com/CDCgov/prime-reportstream/blob/main/SECURITY.md#reporting-a-vulnerability) for more information.**

Test Steps:
1. run ./gradlew testIntegration

## Changes
- *Include a comprehensive list of changes in this PR*
- *(For web UI changes) Include screenshots/video of changes*

## Checklist

### Testing
- [ ] Tested locally?
- [ ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] (For Changes to /frontend-react/...) Ran `npm run lint:write`?
- [ ] Added tests?

### Process
- [ ] Are there licensing issues with any new dependencies introduced?
- [ ] Includes a summary of what a code reviewer should test/verify?
- [ ] Updated the release notes?
- [ ] Database changes are submitted as a separate PR?
- [ ] DevOps team has been notified if PR requires ops support?

## Linked Issues
- Fixes #issue

## To Be Done
*Create GitHub issues to track the work remaining, if any*
- #issue

## Specific Security-related subjects a reviewer should pay specific attention to
- Does this PR introduce new endpoints?
    - new endpoint A
    - new endpoint B
- Does this PR include changes in authentication and/or authorization of existing endpoints?
- Does this change introduce new dependencies that need vetting?
- Does this change require changes to our infrastructure?
- Does logging contain sensitive data?
- Does this PR include or remove any sensitive information itself?

If you answered '_yes_' to any of the questions above, conduct a detailed Review that addresses at least:

- What are the potential security threats and mitigations? Please list the _STRIDE_ threats and how they are mitigated
    - **S**poofing (faking authenticity)
        - Threat _T_, which could be achieved by _A_, is mitigated by _M_
    - **T**ampering (influence or sabotage the integrity of information, data, or system)
    - **R**epudiation (the ability to dispute the origin or originator of an action)
    - **I**nformation disclosure (data made available to entities who should not have it)
    - **D**enial of service (make a resource unavailable)
    - **E**levation of Privilege (reduce restrictions that apply or gain privileges one should not have)
- Have you ensured logging does not contain sensitive data?
- Have you received any additional approvals needed for this change?

2025-01-02 17:31 UTC, jack-h-wang requested changes

2025-01-02 17:31 UTC, jack-h-wang commented on prime-router/src/main/kotlin/azure/BlobAccess.kt
> +        fun copyBlob(fromBlobUrl: String): ByteArray {
This change essentially turns `copyBlob` into a copy of `downloadBlobAsByteArray` except with one extra line of logging. Why not call `downloadBlobAsByteArray` directly? If we don't need `copyBlob` after doing that, then we could delete it (and its test) entirely.

I think it's also worth pointing out the `digest` parameter for `downloadBlob` is available (as `BlobUtils.digestToString(header.reportFile.blobDigest)`) though the return type for that function is `String` instead of `ByteArray`. Performing that bit of verification might make sense?

2025-01-03 16:50 UTC, GilmoreA6 commented on prime-router/src/main/kotlin/azure/BlobAccess.kt
> +        fun copyBlob(fromBlobUrl: String): ByteArray {
@jack-h-wang agree with getting rid of the copyBlob, clarification re: the digest parameter, are you thinking that we should compare the blobDigest to the output to make sure they are the same?

2025-01-03 17:36 UTC, GilmoreA6 commented on prime-router/src/main/kotlin/azure/BlobAccess.kt
> +        fun copyBlob(fromBlobUrl: String): ByteArray {
@jack-h-wang updated to call downloadBlobAsByteArray directly and removed copyBlob and associated tests. We discussed added the compare between the digest and a digest of the downloaded blob but because digestToString has a limit of 40 we thought it added complexity without really verifying much. Happy to still add if you think it's necessary.

2025-01-03 17:43 UTC, jack-h-wang approved these changes

2025-01-03 18:50 UTC, jalbinson commented on prime-router/src/main/kotlin/transport/BlobStoreTransport.kt
> +            val blobFile = BlobAccess.downloadBlobAsByteArray(bodyUrl)
Outside the scope of this ticket/bugfix but I think a better approach would be to use the blob client to copy the blob within Azure instead of download and then upload. It looks like there are some APIs that could accomplish this:

https://learn.microsoft.com/en-us/java/api/com.azure.storage.blob.specialized.blobclientbase?view=azure-java-stable#com-azure-storage-blob-specialized-blobclientbase-copyfromurl(java-lang-string)

2025-01-03 18:51 UTC, jalbinson approved these changes
Alternative approach suggested but not required.

2025-01-07 19:20 UTC, merged