Experience 16074: Create test result page without download results
CDCgov/prime-reportstream pull request #16938
Opened 2024-12-31 23:26 UTC by etanb

Fixes #16074

2024-12-31 23:45 UTC, etanb commented
@jpandersen87 I chose to go with the single `<form>` approach for simplicity. I believe it helps with readability while centralizing the code logic a bit more. 

I 100% appreciate that in React v19 there's a new potential approach to forms, but I think we should focus on the feature at hand, and make a ticket to update our forms across the board if that's something we want to prioritize. I also consolidated some of the componentized pieces you broke out since they were small enough that I felt like it actually added complexity to go search for them (ie, `TestMessageLabel`, `MessageTestingBody` etc).

Currently, this code uses `AdminMessageTestingPage` as a parent / wrapper component, and then it chooses between the two steps within the `MessageTestingSteps` `enum`. I've created a new hook called `useTestMessageResult` to get the validation from the B/E, but we have a little back-and-forth going if requests that don't have the correct responseType or other errors, should be `400` (which they currently are) or if they should be `200` with the issue as a response.

2025-01-07 02:58 UTC, jpandersen87 requested changes

2025-01-07 02:58 UTC, jpandersen87 commented on frontend-react/src/pages/admin/AdminMessageTestingPage/AdminMessageTestingPage.tsx
> +    if (isDisabled) {
We have a component wrapper `RequireGate` that can be used around this at the Router file level rather than doing it inside a page component. Though, if this is properly inserted inside the admin tree of the route object the check is likely already happening for us.

2025-01-07 02:58 UTC, jpandersen87 commented on frontend-react/src/hooks/api/messages/UseTestMessageResult/UseTestMessageResult.ts
> +import { useQuery } from "@tanstack/react-query";
Should be using `useSuspenseQuery`

2025-01-07 02:58 UTC, jpandersen87 commented on frontend-react/src/pages/admin/AdminMessageTestingPage/AdminMessageTestingPage.tsx
> +                    {isLoading ? (
The loading condition will never be true under suspense, as the component will not be rendered until the data is fetched.

2025-01-07 02:58 UTC, jpandersen87 commented on frontend-react/src/hooks/api/messages/UseTestMessageResult/UseTestMessageResult.ts
> +    return {
Please return everything as-is from the hook, adding on anything else we want.

2025-01-07 15:58 UTC, etanb commented on frontend-react/src/hooks/api/messages/UseTestMessageResult/UseTestMessageResult.ts
> +    return {
This is actually an option within the `useQuery` hook that allows us to manually refetch the data: https://tanstack.com/query/v4/docs/framework/react/reference/useQuery.

2025-01-09 06:14 UTC, etanb commented
@jillian-hammer updated top comment with full-page images of each state, parity with Figma design.

2025-01-09 18:09 UTC, etanb commented on frontend-react/src/pages/admin/AdminMessageTestingPage/AdminMessageTestingPage.tsx
> +    if (isDisabled) {
Ah yes, this is redundant since page sits under:

```
path: "admin",
                element: (
                    <RequireGate auth={PERMISSIONS.PRIME_ADMIN}>
                        <Outlet />
                    </RequireGate>
                ),
```

as a child component. Will remove.

2025-01-09 18:41 UTC, jillian-hammer commented
thanks @etanb for the work & the screen recordings!! this is looking good!

missing states
- [ ] Do you have a view with Warnings? I think the screenshots only cover the Error and Success states.
- [ ] Does the **Filters triggered** section have the subsections for **Quality filter** and **Condition filter** built in? I don't see the current example being categorized as one or the other.

UX QA
- [ ] After a user adds a custom message, can it then be auto-selected for them? (Reduces the need for multiple clicks at :07 in the screen recording). if this is more of a message bank comment lmk and we can hold on this.
- [ ] The **Output message** should not appear if there are Errors. in other words, the Output message only appears if A) It passes with warnings or B) It passes successfully. 

content QA
- [ ] "Receiver transform warnings" should read "Transform warnings"
- [ ] "Filter errors" should read "Filters triggered"

2025-01-11 00:35 UTC, etanb commented
@jillian-hammer made those updates (except Filter Trigger subsection since we need [this ticket ](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/17038)to be resolved first) with video proof:


https://github.com/user-attachments/assets/812ec984-044e-44b5-acc4-3ffd9356975a

2025-01-16 16:27 UTC, jpandersen87 commented on frontend-react/src/hooks/api/messages/UseTestMessageResult/UseTestMessageResult.ts
> +import { useQuery } from "@tanstack/react-query";
hmm ok, then we're due for potentially refactoring our code to move enabled logic out of the hooks and into the components

2025-01-16 16:30 UTC, jpandersen87 commented on frontend-react/src/hooks/api/messages/UseTestMessageResult/UseTestMessageResult.ts
> +    return {
Our hooks need to always return everything the useQuery/useSuspenseQuery/useMutation hooks return and only add additional properties

2025-01-16 16:31 UTC, jpandersen87 commented on frontend-react/src/pages/admin/AdminMessageTestingPage/AdminMessageTestingPage.tsx
> +                    {isLoading ? (
Correct, this was written alongside another note about using useSuspenseQuery that is no longer relevant

2025-01-16 16:37 UTC, jpandersen87 requested changes
I think just the issue with returning the original tanquery hook data + custom properties on our hook is left.

2025-01-23 22:48 UTC, jpandersen87 approved these changes

2025-01-24 00:38 UTC, merged