Removed the need to have the local REDOX secret in configuration
CDCgov/prime-reportstream pull request #1970
Opened 2021-08-24 20:42 UTC by carlosfelix2

This PR removes the need to have the local REDOX secret in configuration.  This was generating an error on the Git Leaks pre-hook.

## Changes
- Set a default secret key in the code only for local environment.

## Checklist

### Testing
- [ ] Tested locally?
- [ ] Ran `quickTest all`?
- [ ] Ran `./prime test` against local Docker ReportStream container?
- [ ] Downloaded a file from `http://localhost:7071/api/download`?
- [ ] Added tests?

### Specific Security-relate
### Process
- [ ] Are there licensing issues with any new dependencies introduced?
- [ ] Includes a summary of what a code reviewer should verify?
- [ ] Updated the release notes?
- [ ] Database changes are submitted as a separate PR?
- [ ] DevOps team has been notified if PR requires ops support?

## Fixes

## To Be Done

2021-08-24 22:04 UTC, td-usds commented on prime-router/build.gradle.kts
> -            "REDOX_SECRET" to "some_secret",
Note that just yanking this does not obviate the need to suppress the warning; the nightly run checks the history, not just the state of master as is. In other words, unless you supress this one, the nightly gitleaks run will continue to flag this.

2021-08-24 22:04 UTC, td-usds commented on prime-router/docker-compose.yml
> -      - REDOX_SECRET=some_secret
see above

2021-08-24 22:05 UTC, td-usds commented
I don't know if this is the branch on which you keep seeing the terraform formatting errors, but when I jumped on to this branch, and then git merged master, I no longer see those errors on git commit

2021-08-25 12:03 UTC, jimduff-usds approved these changes
lgtm

2021-08-25 12:38 UTC, td-usds requested changes
Note that you will still have to provide suppressions for the lines you remove since GitLeaks scans history, not 'current state'.
Please include those as well since they are preventing others from merging things in (and so I'd like it in sooner rather than later).

2021-08-25 13:18 UTC, carlosfelix2 commented
> Note that you will still have to provide suppressions for the lines you remove since GitLeaks scans history, not 'current state'.
> Please include those as well since they are preventing others from merging things in (and so I'd like it in sooner rather than later).

You will need to explain how to add suppression.

2021-08-25 13:40 UTC, ronaldheft-usds commented
> > Note that you will still have to provide suppressions for the lines you remove since GitLeaks scans history, not 'current state'.
> > Please include those as well since they are preventing others from merging things in (and so I'd like it in sooner rather than later).
> 
> You will need to explain how to add suppression.

It's documented here: https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/allowlist-gitleaks-false-positives.md

2021-08-25 14:28 UTC, carlosfelix2 commented
> > > Note that you will still have to provide suppressions for the lines you remove since GitLeaks scans history, not 'current state'.
> > > Please include those as well since they are preventing others from merging things in (and so I'd like it in sooner rather than later).
> > 
> > 
> > You will need to explain how to add suppression.
> 
> It's documented here: https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/allowlist-gitleaks-false-positives.md

thanks!

2021-08-25 14:37 UTC, td-usds approved these changes

2021-08-25 14:39 UTC, td-usds approved these changes

2021-08-25 15:13 UTC, merged