Update To LIVD table
CDCgov/prime-reportstream pull request #2915
Opened 2021-11-03 16:38 UTC by jorg3lopez

This PR updates the LIVD table.

Test Steps:
1. Run ./gradlew
   - test
   - testIntegration
   - testEnd2End 

## Changes
- Uploaded the newest LIVD table and renamed it to LIVD-SARs-CoV-2-lastes.csv
- Renamed the old LIVD table to LIVD-SARs-CoV-2-old-1.csv
- Ran generatedocs
- Verified values against the supplemental table to see if they were unchanged (no changes)

## Checklist

### Testing
- [x] Tested locally?
- [x] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] (For Changes to /frontend-react/...) Ran `npm run lint:write`? 
- [ ] Added tests?

## Fixes
- #

## To Be Done
*Create GitHub issues to track the work remaining, if any*
- #issue

## Specific Security-related subjects a reviewer should pay specific attention to
- Does this PR introduce new endpoints?
    - new endpoint A
    - new endpoint B
- Does this PR include changes in authentication and/or authorization of existing endpoints?
- Does this change introduce new dependencies that need vetting?
- Does this change require changes to our infrastructure?
- Does logging contain sensitive data?
- Does this PR include or remove any sensitive information itself?

If you answered '_yes_' to any of the questions above, conduct a detailed Review that addresses at least:

- What are the potential security threats and mitigations? Please list the _STRIDE_ threats and how they are mitigated
    - **S**poofing (faking authenticity)
        - Threat _T_, which could be achieved by _A_, is mitigated by _M_
    - **T**ampering (influence or sabotage the integrity of information, data, or system)
    - **R**epudiation (the ability to dispute the origin or originator of an action)
    - **I**nformation disclosure (data made available to entities who should not have it)
    - **D**enial of service (make a resource unavailable)
    - **E**levation of Privilege (reduce restrictions that apply or gain privileges one should not have)
- Have you ensured logging does not contain sensitive data?
- Have you received any additional approvals needed for this change?

2021-11-03 18:09 UTC, jorg3lopez commented
Working to fix some of the test cases.

2021-11-05 16:20 UTC, carlosfelix2 requested changes

2021-11-05 16:20 UTC, carlosfelix2 commented on prime-router/build.gradle.kts
> +    setForkEvery(1)
What does this do?  Per documentation:
By default, Gradle automatically uses a separate JVM when executing tests, so changing this property is usually not necessary.

2021-11-05 16:20 UTC, carlosfelix2 commented on prime-router/metadata/tables/LIVD-SARS-CoV-2-old-1.csv
> +Manufacturer,Model,Vendor Analyte Name,Vendor Specimen Description,Vendor Result Description,Test Performed LOINC Code,Test Performed LOINC Long Name,Test Ordered LOINC Code,Test Ordered LOINC Long N
From the name, it sounds like this file should be deleted.  All other tables have a date.  I do not think this should be checked in

2021-11-05 16:20 UTC, carlosfelix2 commented on prime-router/metadata/tables/LIVD-SARS-CoV-2-2021-10-27.csv
> +Manufacturer,Model,Vendor Analyte Name,Vendor Specimen Description,Vendor Result Description,Test Performed LOINC Code,Test Performed LOINC Long Name,Test Ordered LOINC Code,Test Ordered LOINC Long N
Is this the same as the latest table?  if it is then I suggest not having duplicate files.

2021-11-05 16:20 UTC, carlosfelix2 commented on prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
> +    @Ignore
Why are these tests being ignored?

2021-11-05 16:49 UTC, jorg3lopez commented
Blocked: We are still testing an issue were one of the tests hangs ( `test incorrect HL7 content`). This causes the heap to run out of memory and it crashes. @RickHawesUSDS  is helping me out on it, as I had to switch to state support. Right now, it will not hang as I'm forking a jvm per test case. This is only for testing purposes, and this branch should not be merge as it stands right now.

2021-11-05 22:25 UTC, jorg3lopez commented
Will close it until I we figure out what's happening with the hanging test case.

2021-11-05 22:25 UTC, closed without merging