1911 - Fixed Patient_age display negative
CDCgov/prime-reportstream pull request #2937
Opened 2021-11-05 11:35 UTC by oslynn

- Fixed the PatientAge in Report.kt
    - Added the Unit Test for checking
      Patient Age.

This PR ...

**If you are suggesting a fix for a currently exploitable issue, please disclose the issue to the prime-reportstream team directly outside of GitHub instead of filing a PR, so we may immediately patch the affected systems before a disclosure. See [SECURITY.md/Reporting a Vulnerability](https://github.com/CDCgov/prime-reportstream/blob/master/SECURITY.md#reporting-a-vulnerability) for more information.**

Test Steps:
1. *Include steps to test these changes*

## Changes
- *Include a comprehensive list of changes in this PR*
- *(For web UI changes) Include screenshots/video of changes*

## Checklist

### Testing
- [ ] Tested locally?
- [ ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] (For Changes to /frontend-react/...) Ran `npm run lint:write`? 
- [ ] Added tests?

### Process
- [ ] Are there licensing issues with any new dependencies introduced?
- [ ] Includes a summary of what a code reviewer should test/verify?
- [ ] Updated the release notes?
- [ ] Database changes are submitted as a separate PR?
- [ ] DevOps team has been notified if PR requires ops support?

## Fixes
- #issue - List GitHub issues this PR fixes

## To Be Done
*Create GitHub issues to track the work remaining, if any*
- #issue

## Specific Security-related subjects a reviewer should pay specific attention to
- Does this PR introduce new endpoints?
    - new endpoint A
    - new endpoint B
- Does this PR include changes in authentication and/or authorization of existing endpoints?
- Does this change introduce new dependencies that need vetting?
- Does this change require changes to our infrastructure?
- Does logging contain sensitive data?
- Does this PR include or remove any sensitive information itself?

If you answered '_yes_' to any of the questions above, conduct a detailed Review that addresses at least:

- What are the potential security threats and mitigations? Please list the _STRIDE_ threats and how they are mitigated
    - **S**poofing (faking authenticity)
        - Threat _T_, which could be achieved by _A_, is mitigated by _M_
    - **T**ampering (influence or sabotage the integrity of information, data, or system)
    - **R**epudiation (the ability to dispute the origin or originator of an action)
    - **I**nformation disclosure (data made available to entities who should not have it)
    - **D**enial of service (make a resource unavailable)
    - **E**levation of Privilege (reduce restrictions that apply or gain privileges one should not have)
- Have you ensured logging does not contain sensitive data?
- Have you received any additional approvals needed for this change?

2021-11-05 16:12 UTC, carlosfelix2 approved these changes
PR description needs to be populated correctly

2021-11-05 16:12 UTC, carlosfelix2 commented on prime-router/src/main/kotlin/Report.kt
> +                                (d.isBefore(it.specimenCollectionDateTime))
Add a quick comment just saying why you are using DOB to check the date.

2021-11-05 16:12 UTC, carlosfelix2 commented on prime-router/src/test/kotlin/ReportTests.kt
> +            listOf("3", "adfadf", "!@!*@(7"),               // Garbage -> patient_age = null
Nice!

2021-11-05 17:09 UTC, jimduff-usds requested changes
Does not meet acceptance criteria -- Needs to use patient_age if it exists.  This was repeated twice in the acceptance criteria of the ticket:

- As part of the fix, add a test to see if the incoming data has a patient_age value. If it does, just use it as-is. If not, then attempt to calculate using patient_dob.
- use the incoming patient_age is used, if it exists and is valid. (Is a number greater than zero)

2021-11-08 20:53 UTC, jimduff-usds approved these changes

2021-11-16 22:54 UTC, clediggins-usds approved these changes

2021-11-17 22:46 UTC, merged