Add `.limit()` to queries to bound them
CDCgov/prime-reportstream pull request #6305
Opened 2022-08-03 18:51 UTC by TomNUSDS

Fixes #6304

Test Steps:
1. Query for a large amount of data (e.g. `api/adm/listreceiversconnstatus?start_date=2020-01-01T00:00:00.000Z`)
2. Verify only 9000 rows are returned. (Note most localhost devs don't have enough much data in them.)
Using UI
1. Log in as a Prime Admin
2. Go to `admin/send-dash` (menu: Admin-> Receiver Status Dashboard)
3. Select an earlier starting date (say 5 weeks back).
WARNING: HTML Render of this much data is slow in the browser. (separate client-side fix pending).
4. Check query only returns 9000 rows.

## Changes
- Added a `.limit(9000)` to two queries: 

## Checklist

### Testing
- [x] Tested locally?
- [x] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [x] (For Changes to /frontend-react/...) Ran `npm run lint:write`? 
[ ] ~Added tests?~ Not sure how to test a limit of 9000 rows?

### Process
- [ ] Are there licensing issues with any new dependencies introduced?
- [ ] Includes a summary of what a code reviewer should test/verify?
- [ ] Updated the release notes?
- [ ] Database changes are submitted as a separate PR?
- [ ] DevOps team has been notified if PR requires ops support?

## Linked Issues
- Fixes #6304

## To Be Done
*Create GitHub issues to track the work remaining, if any*
- #6288 and #6303

## Specific Security-related subjects a reviewer should pay specific attention to
> (No to all)
- Does this PR introduce new endpoints?
    - new endpoint A
    - new endpoint B
- Does this PR include changes in authentication and/or authorization of existing endpoints?
- Does this change introduce new dependencies that need vetting?
- Does this change require changes to our infrastructure?
- Does logging contain sensitive data?
- Does this PR include or remove any sensitive information itself?

If you answered '_yes_' to any of the questions above, conduct a detailed Review that addresses at least:

- What are the potential security threats and mitigations? Please list the _STRIDE_ threats and how they are mitigated
    - **S**poofing (faking authenticity)
        - Threat _T_, which could be achieved by _A_, is mitigated by _M_
    - **T**ampering (influence or sabotage the integrity of information, data, or system)
    - **R**epudiation (the ability to dispute the origin or originator of an action)
    - **I**nformation disclosure (data made available to entities who should not have it)
    - **D**enial of service (make a resource unavailable)
    - **E**levation of Privilege (reduce restrictions that apply or gain privileges one should not have)
- Have you ensured logging does not contain sensitive data?
- Have you received any additional approvals needed for this change?

2022-08-08 16:13 UTC, carlosfelix2 requested changes
Pipeline team talked about this and we think it is better to enforce pagination on both the API and DB level instead of providing a max limit that does not report to a user when data is truncated.

2022-08-08 18:07 UTC, TomNUSDS commented
@carlosfelix2 
> Pipeline team talked about this and we think it is better to enforce pagination on both the API and DB level instead of providing a max limit that does not report to a user when data is truncated.

So if the API request is too big, then return a `413 Payload Too Large` https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/413 ?

2022-08-08 19:48 UTC, TomNUSDS commented
@carlosfelix2 

tldr; I'd like to push back on getting this PR approved as is. It's not perfect, but it's an improvement on what's in production now and it's simple fix and it only impacts an API used by DHPrimeAdmins.

Longer:
Doing a more detailed sanity check is tricky. API level preflighting for `api/adm/listreceiversconnstatus` cannot determine the size of the resulting query reliability since that depends how often the CRON job is running AND the number of Receivers being checked in additions to the date range.

I have another PR (#6315) that enforced the # of days on the client and this API endpoint is ONLY for DHPrimeAdmins.

2022-08-10 14:16 UTC, carlosfelix2 approved these changes

2022-08-10 15:18 UTC, merged