MSH segment
CDCgov/prime-reportstream pull request #6423
Opened 2022-08-18 16:59 UTC by clediggins-usds

This PR adds the configuration to generate the MSH HL7 segment from a fhir document as well as updates a few missing/incorrect fields in FHIR generation.

Test Steps:
1. Run the fhirdata command on a FHIR file and compare the output to the input hl7 for the MSH segment.

## Changes
- Add extensions for the destination element for receiving facility and application id
- Fixes two FHIR generation items to get correct ids
- adds extensions for receiving application and facility within Destination element

### Testing
- [x] Tested locally?

2022-08-18 19:24 UTC, TurkeyFried commented
There's a little missing on the output HL7: `||||PHLabReport-NoAck^HL7^2.16.840.1.113883.9.11^ISO`

Everything up to that point is perfect.

2022-08-18 20:12 UTC, TurkeyFried approved these changes

2022-08-22 14:50 UTC, PatriciaPerozoUSDS commented on prime-router/metadata/fhir_mapping/hl7/secondary/Destination.yml
> +name:
I'm curious if there was a reason destination wasn't mapped in the first pass. Totally not blocking at at all but would want to know if there is any historical knowledge on this.

2022-08-22 14:54 UTC, PatriciaPerozoUSDS commented on prime-router/metadata/fhir_mapping/hl7/secondary/Destination.yml
> +name:
Also do we need to update the mapping spreadsheet to reflect that we've added this?

2022-08-23 14:33 UTC, carlosfelix2 requested changes

2022-08-23 14:33 UTC, carlosfelix2 commented on prime-router/metadata/fhir_mapping/hl7/secondary/Destination.yml
> +  condition: $idStr NOT_NULL && $systemStr EQUALS ISO
FYI: Note we will need to support CLIA soon

2022-08-23 14:33 UTC, carlosfelix2 commented on prime-router/metadata/hl7_mapping/ORU_R01/base/message-header.yml
> +    value: [ '''ISO''' ]
You need to check that the ID is an OID.  See example in the SFT segment.

2022-08-23 14:33 UTC, carlosfelix2 commented on prime-router/metadata/hl7_mapping/ORU_R01/base/message-header.yml
> +    value: [ '''ISO''' ]
You need to check that the ID is an OID. See example in the SFT segment.

2022-08-23 14:33 UTC, carlosfelix2 commented on prime-router/metadata/hl7_mapping/ORU_R01/base/message-header.yml
> +    value: [ '''ISO''' ]
You need to check that the ID is an OID. See example in the SFT segment.

2022-08-23 14:33 UTC, carlosfelix2 commented on prime-router/metadata/hl7_mapping/ORU_R01/base/message-header.yml
> +    value: [ '''ISO''' ]
You need to check that the ID is an OID. See example in the SFT segment.

2022-08-23 14:35 UTC, carlosfelix2 requested changes

2022-08-23 14:35 UTC, carlosfelix2 commented on prime-router/metadata/hl7_mapping/ORU_R01/base/message-header.yml
> +    hl7Spec: [ MSH-17 ]
Missing MSH-21

2022-08-23 14:38 UTC, carlosfelix2 commented on prime-router/metadata/hl7_mapping/ORU_R01/base/message-header.yml
> +  - name: message-date-time
I opened a new bug to try to fix this offset changing on the time.

2022-08-23 15:38 UTC, carlosfelix2 approved these changes

2022-08-23 18:45 UTC, merged