Delivery API now based on reports created by the Batch step
CDCgov/prime-reportstream pull request #6632
Opened 2022-09-05 19:54 UTC by jimduff-usds

This PR contains various fixes to the Delivery API, to wit:
- The biggest change is that calls to the various delivery and deliveries endpoints now return (or take as input) reports created by the `batch` step.   The previous iteration of this API returned reports created by the `send` step.   That was wrong - the main use case for the delivery API is for the download website, which, tautologically, lists reports that have NOT been downloaded or sent.  Note:   undoubtedly there's a future use case floating out there to list all the ways a single report leaving the `batch` step has been delivered, but that's a different use case than the "Daily Data" page use case we're trying to meet here.
- clarified in the api docs that you limit the number of results using `pagesize`, not `pageSize`.

Made the following changes to the responses to the `api/waters/org/ORG.RECEIVER/list` endpoint:
- replaced `receivingOrg` and `receivingOrgSvc` with `receiver`, which is the fullName, eg, `md-phd.elr`.
- replaced `sent` with `batchReadyAt` timestamp, which is accurate at least, while not terribly interesting to the user.  They want to know when it was sent, which as I said, is a different query.
- Fixed both `reportItemCount` and `topic` which were null.
- Removed `externalName`, which is null for reports leaving the `batch` step.

Here's an example query and response to that endpoint, as it now appears:

```
curl "http://localhost:7071/api/waters/org/md-phd.elr/deliveries?pagesize=1" 

[ {
  "deliveryId" : 3389,
  "batchReadyAt" : "2022-08-25T14:14:00.459Z",
  "expires" : "2022-09-24T14:14:00.459Z",
  "receiver" : "md-phd.elr",
  "reportId" : "00a7717d-e543-4802-8d53-00f922f20ba3",
  "topic" : "covid-19",
  "reportItemCount" : 15,
  "fileName" : "covid-19-00a7717d-e543-4802-8d53-00f922f20ba3-20220825101400.hl7",
  "fileType" : "HL7_BATCH"
} ]
```

**If you are suggesting a fix for a currently exploitable issue, please disclose the issue to the prime-reportstream team directly outside of GitHub instead of filing a PR, so we may immediately patch the affected systems before a disclosure. See [SECURITY.md/Reporting a Vulnerability](https://github.com/CDCgov/prime-reportstream/blob/master/SECURITY.md#reporting-a-vulnerability) for more information.**

Test Steps:
1. *Include steps to test these changes*

## Changes
- *Include a comprehensive list of changes in this PR*
- *(For web UI changes) Include screenshots/video of changes*

## Checklist

### Testing
- [ ] Tested locally?
- [ ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] (For Changes to /frontend-react/...) Ran `npm run lint:write`? 
- [ ] Added tests?

### Process
- [ ] Are there licensing issues with any new dependencies introduced?
- [ ] Includes a summary of what a code reviewer should test/verify?
- [ ] Updated the release notes?
- [ ] Database changes are submitted as a separate PR?
- [ ] DevOps team has been notified if PR requires ops support?

## Linked Issues
- Fixes #issue

## To Be Done
*Create GitHub issues to track the work remaining, if any*
- #issue

## Specific Security-related subjects a reviewer should pay specific attention to
- Does this PR introduce new endpoints?
    - new endpoint A
    - new endpoint B
- Does this PR include changes in authentication and/or authorization of existing endpoints?
- Does this change introduce new dependencies that need vetting?
- Does this change require changes to our infrastructure?
- Does logging contain sensitive data?
- Does this PR include or remove any sensitive information itself?

If you answered '_yes_' to any of the questions above, conduct a detailed Review that addresses at least:

- What are the potential security threats and mitigations? Please list the _STRIDE_ threats and how they are mitigated
    - **S**poofing (faking authenticity)
        - Threat _T_, which could be achieved by _A_, is mitigated by _M_
    - **T**ampering (influence or sabotage the integrity of information, data, or system)
    - **R**epudiation (the ability to dispute the origin or originator of an action)
    - **I**nformation disclosure (data made available to entities who should not have it)
    - **D**enial of service (make a resource unavailable)
    - **E**levation of Privilege (reduce restrictions that apply or gain privileges one should not have)
- Have you ensured logging does not contain sensitive data?
- Have you received any additional approvals needed for this change?

2022-09-23 13:53 UTC, kevinhaube commented
<img width="572" alt="Screen Shot 2022-09-23 at 9 44 56 AM" src="https://user-images.githubusercontent.com/4022304/191975720-9f21e1b8-576a-412a-88af-a5659f71a681.png">
I was getting `null` in the response for `reportItemCount`

2022-09-26 20:27 UTC, kevinhaube approved these changes

2022-09-27 16:45 UTC, doug-s-nava requested changes
One failing test here - I added an `initialized` param that needs to be accounted for in one of the tests

2022-09-27 16:49 UTC, doug-s-nava reviewed
oops one more lil comment

2022-09-27 16:49 UTC, doug-s-nava commented on frontend-react/package.json
> +        "test": "react-scripts test --silent",
this should come out

2022-09-27 19:25 UTC, doug-s-nava approved these changes
✅ ✅ ✅

2022-09-28 12:13 UTC, merged