Generate SPM segments from FHIR
CDCgov/prime-reportstream pull request #6653
Opened 2022-09-07 16:39 UTC by PatriciaPerozoUSDS

This PR ...
- Adds the generation of the SPM segment
- Adds a "coded with exceptions" CWE HL7 mapping helper.

Test Steps:
1. Run the FHIR -> HL7 conversion command ```./gradlew primeCLI --args='fhirdata --input-file "src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001.fhir" -s metadata/hl7_mapping/ORU_R01/ORU_R01-base.yml'```
2. You will notice these differences:
- SPM.2.2.4 Doesn't include ISO . This follows the previous decision not to include ISO if the universal id is not included
- SPM.14 only includes RA, This is noted in the mapping and is due to the fact that HCA is supposed to be sending us text but instead is sending a CE
- SPM.26. In the sample file some numbers are ints while others are doubles. The output of the generated HL7 is always a double.

## Changes
- Adds the generation of the SPM segment
- Adds a "coded with exceptions" CWE HL7 mapping helper.
- Adds a None concept to the CodingSystemMapper so throw an exception if there is no mapping.

## Checklist

### Testing
- [X] Tested locally?
- [ ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] (For Changes to /frontend-react/...) Ran `npm run lint:write`? 
- [ ] Added tests?

## Linked Issues
- #5755

2022-09-07 16:40 UTC, PatriciaPerozoUSDS commented on prime-router/metadata/hl7_mapping/ORU_R01/base/order-observation.yml
> -  - name: request-set-ID
This was also duplicated in the observation-request schema. It seems more appropriate to stay there.

2022-09-08 16:31 UTC, carlosfelix2 requested changes
Per my test, you are missing SPM-14-2 and SPM-14-3

2022-09-08 16:31 UTC, carlosfelix2 commented on prime-router/metadata/hl7_mapping/ORU_R01/base/coded-with-exceptions.yml
> +    condition: '%resource.exists()'
Remove this condition.  It is already checked by value

2022-09-08 16:31 UTC, carlosfelix2 commented on prime-router/metadata/hl7_mapping/ORU_R01/base/coded-with-exceptions.yml
> +    condition: '%resource.exists()'
Remove this condition. It is already checked by value

2022-09-08 16:33 UTC, carlosfelix2 commented
> Per my test, you are missing SPM-14-2 and SPM-14-3

NM.  You are right.  The type is incorrect from the original data.

2022-09-08 16:33 UTC, carlosfelix2 submitted a review, later dismissed

2022-09-08 21:05 UTC, merged