Cle/7043 juris filter
CDCgov/prime-reportstream pull request #7173
Opened 2022-10-28 23:23 UTC by clediggins-usds

This PR makes universal pipeline routing use fhirPath instead of being hardcoded.

Test Steps:
1. Run tests
OR
1. Set up a local receiver with filters with topic 'full-elr' and add fhirPath to the jurisdisctionalFilter section
2. Submit a message with client headers for a full-elr sender
3. Observe result

## Changes
- 

## Checklist

### Testing
- [x] Tested locally?
- [x] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [x] Added tests?

2022-10-28 23:25 UTC, clediggins-usds commented on prime-router/src/main/kotlin/transport/RESTTransport.kt
> +}
I don't know why this was missing. ktLint caught it after a master merge.

2022-10-31 17:48 UTC, TurkeyFried approved these changes
Tests pass, code is documented and makes sense

2022-10-31 19:35 UTC, carlosfelix2 requested changes

2022-11-01 19:58 UTC, carlosfelix2 approved these changes

2022-11-01 20:13 UTC, merged