Fixed MO Prod data Missing ORC-2.1 and OBR-2.1
CDCgov/prime-reportstream pull request #7470
Opened 2022-11-23 20:44 UTC by oslynn

This PR fixed MO Prod data missing ORC-2.1 and OBR-2.1.  The reason is that Intrivo uses the schema hl7/hl7-ingest-covid-19-prod.schema to send messages to MO.  The schema doesn't map the PrimeDataInput/pdi-covid-19.schema which maps the ORC-2.1 (place_order_id) to message_id.  Therefore, MO receives messages from Intrivo without ORC-2.1 and OBR-2.1.  

Test Steps:
1. ./gradlew clean package
2. using mo-test.hl7 as input
3. ./pime data --input covid-19-input.hl7 --input-schema hl7/hl7-ingest-covid-19-prod --output-dir junk --route
4. Examine the output hl7 to see the ORC-2.1 and OBR-2.1, they should contain the value 351142 which is the MSH-10 value.

Test File: 
[covid-19-input-test.txt](https://github.com/CDCgov/prime-reportstream/files/10079083/covid-19-input-test.txt)

## Changes
- *Include a comprehensive list of changes in this PR*
- *(For web UI changes) Include screenshots/video of changes*

## Checklist

### Testing
- [x] Tested locally?
- [x] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] (For Changes to /frontend-react/...) Ran `npm run lint:write`? 
- [ ] Added tests?

### Process
- [ ] Are there licensing issues with any new dependencies introduced?
- [ ] Includes a summary of what a code reviewer should test/verify?
- [ ] Updated the release notes?
- [ ] Database changes are submitted as a separate PR?
- [ ] DevOps team has been notified if PR requires ops support?

## Linked Issues
- Fixes #issue
- https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/7432

## To Be Done
*Create GitHub issues to track the work remaining, if any*
- #issue

## Specific Security-related subjects a reviewer should pay specific attention to
- Does this PR introduce new endpoints?
    - new endpoint A
    - new endpoint B
- Does this PR include changes in authentication and/or authorization of existing endpoints?
- Does this change introduce new dependencies that need vetting?
- Does this change require changes to our infrastructure?
- Does logging contain sensitive data?
- Does this PR include or remove any sensitive information itself?

If you answered '_yes_' to any of the questions above, conduct a detailed Review that addresses at least:

- What are the potential security threats and mitigations? Please list the _STRIDE_ threats and how they are mitigated
    - **S**poofing (faking authenticity)
        - Threat _T_, which could be achieved by _A_, is mitigated by _M_
    - **T**ampering (influence or sabotage the integrity of information, data, or system)
    - **R**epudiation (the ability to dispute the origin or originator of an action)
    - **I**nformation disclosure (data made available to entities who should not have it)
    - **D**enial of service (make a resource unavailable)
    - **E**levation of Privilege (reduce restrictions that apply or gain privileges one should not have)
- Have you ensured logging does not contain sensitive data?
- Have you received any additional approvals needed for this change?

2022-11-25 19:04 UTC, MauriceReeves-usds requested changes

2022-11-26 15:24 UTC, oslynn commented on prime-router/settings/organizations.yml
> +          OBR-2-1: [ "": "*MSH-10" ]
@MauriceReeves-usds, thank you for reviewing the PR:  I added a comment in the PR above.  Please review the above PR's description.

2022-11-26 16:05 UTC, oslynn commented on prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
> +    private fun replaceValueAwithB(
Done.

2022-11-26 16:05 UTC, oslynn commented on prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
> +
Done.

2022-11-28 16:11 UTC, MauriceReeves-usds approved these changes

2022-11-28 19:21 UTC, merged