Cle/7202 up in smoke
CDCgov/prime-reportstream pull request #7699
Opened 2022-12-15 20:44 UTC by clediggins-usds

This PR adds a smoke test for universal pipeline

Test Steps:
1. ./gradlew testSmoke

## Changes
-

## Checklist

### Testing
- [x] Tested locally?
- [x] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [x] Added tests?

2022-12-16 18:36 UTC, carlosfelix2 requested changes
I shutdown the SFTP server and I still got a success on the test.  See normal end2end test

2022-12-16 18:36 UTC, carlosfelix2 commented on prime-router/settings/organizations.yml
> +      jurisdictionalFilter: [ "%performerState = 'CO' or %patientState = 'CO'" ]
Historically, this has been always set to something like `matches(ordering_facility_county, HL7_BATCH)` for receivers used in the smoke tests. Could we do that here too?

2022-12-16 18:36 UTC, carlosfelix2 commented on prime-router/src/main/kotlin/cli/tests/BasicTests.kt
> +class End2EndUniversalPipeline : CoolTest() {
Need kdoc

2023-01-04 01:05 UTC, JessicaWNava reviewed
Tested and it worked. At least to the level I understand, the changes look good. Thank you for all of the cleanup you did along the way as well!

2023-01-04 01:05 UTC, JessicaWNava commented on prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
> +                val sql = """
Thank you for letting me rubber duck with you on this, it actually makes sense when it definitely would not have otherwise.

2023-01-04 02:17 UTC, TurkeyFried approved these changes
Tests pass, I see the kdoc has been added, looks good!

2023-01-06 19:11 UTC, carlosfelix2 approved these changes

2023-01-10 17:02 UTC, merged