Remove the GAEN Error From Last Mile Failure
CDCgov/prime-reportstream pull request #7830
Opened 2023-01-03 20:00 UTC by oslynn

This PR removes the GAEN error message for the last-mile failure since it can't be resent.  It must be resent via resubmission from the sender.

Test Steps:
1. *Include steps to test these changes*

## Changes
- *Include a comprehensive list of changes in this PR*
- *(For web UI changes) Include screenshots/video of changes*

## Checklist

### Testing
- [ ] Tested locally?
- [ ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [ ] (For Changes to /frontend-react/...) Ran `npm run lint:write`? 
- [ ] Added tests?

### Process
- [ ] Are there licensing issues with any new dependencies introduced?
- [ ] Includes a summary of what a code reviewer should test/verify?
- [ ] Updated the release notes?
- [ ] Database changes are submitted as a separate PR?
- [ ] DevOps team has been notified if PR requires ops support?

## Linked Issues
- Fixes #issue

## To Be Done
*Create GitHub issues to track the work remaining, if any*
- #issue

## Specific Security-related subjects a reviewer should pay specific attention to
- Does this PR introduce new endpoints?
    - new endpoint A
    - new endpoint B
- Does this PR include changes in authentication and/or authorization of existing endpoints?
- Does this change introduce new dependencies that need vetting?
- Does this change require changes to our infrastructure?
- Does logging contain sensitive data?
- Does this PR include or remove any sensitive information itself?

If you answered '_yes_' to any of the questions above, conduct a detailed Review that addresses at least:

- What are the potential security threats and mitigations? Please list the _STRIDE_ threats and how they are mitigated
    - **S**poofing (faking authenticity)
        - Threat _T_, which could be achieved by _A_, is mitigated by _M_
    - **T**ampering (influence or sabotage the integrity of information, data, or system)
    - **R**epudiation (the ability to dispute the origin or originator of an action)
    - **I**nformation disclosure (data made available to entities who should not have it)
    - **D**enial of service (make a resource unavailable)
    - **E**levation of Privilege (reduce restrictions that apply or gain privileges one should not have)
- Have you ensured logging does not contain sensitive data?
- Have you received any additional approvals needed for this change?

2023-01-03 23:16 UTC, GilmoreA6 requested changes

2023-01-03 23:16 UTC, GilmoreA6 commented on prime-router/src/main/kotlin/transport/GAENTransport.kt
> +                // Note: To keep us not to post error in the Last Mile Failure page, we are going to ignore
Just adding a suggestion here to improve this comment for clarity. Something like "The majority of GAEN errors are invalid date content errors that can not be rectified by resubmission via the Last Mile Failures page. We have decided to ignore the 400 error code for GAEN messages as we are not taking action on these errors. This does not affect ELR messages sent to STLTs."

2023-01-06 17:41 UTC, MauriceReeves-usds commented
@oslynn I concur with @GilmoreA6's suggestion above. Please update the documentation so it's clear why we're ignoring certain errors.

2023-01-06 18:59 UTC, GilmoreA6 approved these changes
LGTM

2023-01-06 19:21 UTC, merged