Add user story issue template
CDCgov/prime-reportstream pull request #9228
Opened 2023-04-20 15:59 UTC by arnejduranovic

This PR creates the user story template the platform team uses for all its tickets.

2023-04-20 17:55 UTC, jack-h-wang requested changes
I think it would be better to copy the content of #4932 which seems a little more fleshed out.

2023-04-21 16:05 UTC, JessicaWNava commented on .github/ISSUE_TEMPLATE/platform-user-story.md
> +What is Acceptance Criteria?
Can we move this part of the note down to the acceptance criteria section please?

2023-04-21 16:07 UTC, JessicaWNava approved these changes
One change requested, otherwise looks good! Thanks for this, this will be super helpful!

2023-04-21 16:48 UTC, snesm approved these changes

2023-04-21 18:05 UTC, merged