Correct Submission History to display "Received" and "Not Received" correctly
CDCgov/prime-reportstream pull request #9621
Opened 2023-05-25 19:41 UTC by TurkeyFried

This PR corrects a display bug where the status for Submission History displays `Not Delivering` on reports that will be delivered but do not have Destinations calculated yet.

Test Steps:
1. Submit a report with data that you know will be delivered to at least 1 Receiver
2. Immediately after receiving the `SubmissionId`, use the `History API` to check the status of the report. It should display `Received`
3. Now submit a report with data that you know will not be delivered to any Receivers
4. Immediately after receiving the `SubmissionId`, use the `History API` to check the status of the report. It should display `Not Delivering`

## Changes
- Added a new var to track the total number of items that passed filtering on a submission
- Update `calculateStatus` to use the new var in calculation
- Added a few documentation fixes

## Linked Issues
- #9378

2023-05-30 20:46 UTC, jimmyfagan reviewed
Left a few comments/questions, let me know when this is ready for another look!

2023-05-30 20:46 UTC, jimmyfagan commented on prime-router/src/main/kotlin/history/SubmissionHistory.kt
> +     * Container for the sum of items in total that have passed any filters
Found this wording a little confusing, maybe this instead?
```suggestion
     * Number of items in total that have passed any filters
```

2023-05-30 20:46 UTC, jimmyfagan commented on prime-router/src/main/kotlin/history/SubmissionHistory.kt
> +                return Status.NOT_DELIVERING
Maybe this should be "waiting to deliver" if `itemCountAfterFiltering` is greater than 0?

2023-05-30 20:46 UTC, jimmyfagan commented on prime-router/src/main/kotlin/history/SubmissionHistory.kt
Just curious, did you do some testing of the legacy pipeline on this? It looks like it would be okay for legacy too, but  I don't have as much experience with that, so I didn't know for sure.

2023-05-30 21:47 UTC, jimmyfagan commented on prime-router/src/main/kotlin/history/SubmissionHistory.kt
> +                return Status.NOT_DELIVERING
The acceptance criteria actually does say "received" so I'm fine with this either way!

2023-05-31 18:26 UTC, TurkeyFried commented on prime-router/src/main/kotlin/history/SubmissionHistory.kt
Yeah, running both sync and async on the legacy pipeline gives the expected status with this change

2023-06-01 14:25 UTC, arnejduranovic requested changes
We should have some tests. The reason we had this bug in the first place is because we didn't have tests?

2023-06-01 14:25 UTC, arnejduranovic commented on prime-router/src/main/kotlin/history/SubmissionHistory.kt
> +        descendant.reports?.forEach {
NIT: Why do you need a separate loop for this, why can we not increment the counter inside the same block where we do destinations.add?

2023-06-01 16:19 UTC, arnejduranovic approved these changes

2023-06-01 18:58 UTC, TurkeyFried commented
Came up with a test case that fails with the old logic, then passes with the changes made. Added it on the latest commit

2023-06-01 19:32 UTC, jimmyfagan approved these changes

2023-06-01 19:34 UTC, merged